-- $Id$
-- 3GPP TS 36.423 V8.0.0 (2007-12)
-- 9.3.5	Information Element Definitions
-- **************************************************************
--
-- Information Element Definitions
--
-- **************************************************************

X2AP-IEs {
itu-t (0) identified-organization (4) etsi (0) mobileDomain (0) 
eps-Access (21) modules (3) x2ap (2) version1 (1) x2ap-IEs (2) }

DEFINITIONS AUTOMATIC TAGS ::= 

BEGIN

IMPORTS
	id-InterfacesToTrace-Item,
	maxInterfaces,
	maxNrOfErrors,
	maxnoofCells,
	maxnoofEPLMNs,
	maxnoofEPLMNsPlusOne,
	maxnoofForbLACs,
	maxnoofForbTAIs,
	maxCellineNB,
	maxnoofBPLMNs

FROM X2AP-Constants

	Criticality,
	ProcedureCode,
	ProtocolIE-ID,
	TriggeringMessage
FROM X2AP-CommonDataTypes

	ProtocolIE-Single-Container{},
	ProtocolExtensionContainer{},
	X2AP-PROTOCOL-IES,
	X2AP-PROTOCOL-EXTENSION
FROM X2AP-Containers;

-- A

AggregateMaximumBitRate ::= SEQUENCE {
	aggregateMaximumBitRateDownlink		SAE-Bearer-BitRate,
	aggregateMaximumBitRateUplink		SAE-Bearer-BitRate,
	...
}

AllocationAndRetentionPriority ::= OCTET STRING


-- B

Bearer-ID ::= BIT STRING (SIZE (8))  -- To be checked, FFS

BroadcastPLMNs-Item ::= SEQUENCE (SIZE(1..maxnoofBPLMNs)) OF PLMN-Identity


-- C

Cause ::= CHOICE {
	radioNetwork		CauseRadioNetwork,
	transport			CauseTransport,
	protocol			CauseProtocol,
	misc				CauseMisc,
	...
}

CauseMisc ::= ENUMERATED {
	control-processing-overload,
	hardware-failure,
	om-intervention,
	not-enough-user-plane-processing-resources,
	unspecified,
	...
}

CauseProtocol ::= ENUMERATED {
	transfer-syntax-error,
	abstract-syntax-error-reject,
	abstract-syntax-error-ignore-and-notify,
	message-not-compatible-with-receiver-state,
	semantic-error,
	unspecified,
	abstract-syntax-error-falsely-constructed-message,
	...
}

CauseRadioNetwork ::= ENUMERATED {
	normal-ho,
	emergency-ho,
	load-balancing,
	overload,
	unspecified,
	...

}

CauseTransport ::= ENUMERATED {
	transport-resource-unavailable,
	unspecified,
	...
}

CellType ::= ENUMERATED{ 
	macro, 
	micro, 
	pico, 
	femto,
	...
}

CellId ::= OCTET STRING



CGI ::= SEQUENCE {
	pLMN-Identity			PLMN-Identity,
	lAC						LAC,
	cI						CI,
	iE-Extensions			ProtocolExtensionContainer { {CGI-ExtIEs} } OPTIONAL
}

CGI-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}

CI					::= OCTET STRING (SIZE (2))

CriticalityDiagnostics ::= SEQUENCE {
	procedureCode					ProcedureCode					OPTIONAL,
	triggeringMessage				TriggeringMessage				OPTIONAL,
	procedureCriticality			Criticality						OPTIONAL,
	iEsCriticalityDiagnostics		CriticalityDiagnostics-IE-List	OPTIONAL,
	iE-Extensions					ProtocolExtensionContainer { {CriticalityDiagnostics-ExtIEs} } OPTIONAL,
	...
}

COUNTvalue ::= SEQUENCE {
	pDCP-SN			PDCP-SN,
	hFN				HFN,
	...
}

CriticalityDiagnostics-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}

CriticalityDiagnostics-IE-List ::= SEQUENCE (SIZE (1..maxNrOfErrors)) OF
	SEQUENCE {
		iECriticality			Criticality,
		iE-ID					ProtocolIE-ID,
		typeOfError				TypeOfError,
		iE-Extensions			ProtocolExtensionContainer { {CriticalityDiagnostics-IE-List-ExtIEs} } OPTIONAL,
		...
	}

CriticalityDiagnostics-IE-List-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}



-- D

DL-data-received ::= INTEGER

DL-Forwarding ::= ENUMERATED {
	dL-forwardingProposed,
	...
}

-- E

ENB-Global-ID		::= INTEGER (0..65535)  -- Value to be checked FFS

EPLMNs ::= SEQUENCE (SIZE(1..maxnoofEPLMNs)) OF PLMN-Identity


-- F

ForbiddenInterRATs ::= ENUMERATED {
	all,
	geran,
	utran,
	...
}

ForbiddenTAs ::= SEQUENCE (SIZE(1.. maxnoofEPLMNsPlusOne)) OF ForbiddenTAs-Item

ForbiddenTAs-Item ::= SEQUENCE {
	pLMN-Identity		PLMN-Identity,
	forbiddenTAIs		ForbiddenTAIs
}

ForbiddenTAIs ::= SEQUENCE (SIZE(1..maxnoofForbTAIs)) OF TAI

ForbiddenLAs ::= SEQUENCE (SIZE(1..maxnoofEPLMNsPlusOne)) OF ForbiddenLAs-Item

ForbiddenLAs-Item ::= SEQUENCE {	
	pLMN-Identity		PLMN-Identity,
	forbiddenLACs		ForbiddenLACs
}

ForbiddenLACs ::= SEQUENCE (SIZE(1..maxnoofForbLACs)) OF LAC

Frequency ::= OCTET STRING


-- G


GTPtunnelEndpoint ::= SEQUENCE {
	transportLayerAddress			TransportLayerAddress,
	gTP-TEID						GTP-TEI,
	iE-Extensions					ProtocolExtensionContainer { {GTPtunnelEndpoint-ExtIEs} } OPTIONAL,
	...
}

GTPtunnelEndpoint-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}

GTP-TEI					::= OCTET STRING (SIZE (4))

GUMMEI			::= SEQUENCE {
	pLMN-Identity		PLMN-Identity,
	mME-Group-ID		MME-Group-ID,
	mMME-Code			MME-Code,
	iE-Extensions					ProtocolExtensionContainer { {GUMMEI-ExtIEs} } OPTIONAL,
	...
}

GUMMEI-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}



-- H

HandoverRestrictionList ::= SEQUENCE {
	equivalentPLMNs				EPLMNs					OPTIONAL,
	forbiddenTAs				ForbiddenTAs			OPTIONAL,
	forbiddenLAs				ForbiddenLAs			OPTIONAL,
	forbiddenInterRATs			ForbiddenInterRATs		OPTIONAL, 
	iE-Extensions				ProtocolExtensionContainer { {HandoverRestrictionList-ExtIEs} } OPTIONAL,
	...
}

HandoverRestrictionList-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}

HFN ::= INTEGER (0..1048575)



-- I


InterfacesToTrace ::= SEQUENCE (SIZE(0..maxInterfaces)) OF ProtocolIE-Single-Container {{InterfacesToTrace-ItemIEs} }

InterfacesToTrace-ItemIEs X2AP-PROTOCOL-IES ::= {
	{ ID id-InterfacesToTrace-Item	CRITICALITY ignore	TYPE InterfacesToTrace-Item 	PRESENCE mandatory	}
}

InterfacesToTrace-Item ::= SEQUENCE {
	traceInterface					TraceInterface,
	traceDepth						TraceDepth,
	iE-Extensions					ProtocolExtensionContainer { {InterfacesToTrace-Item-ExtIEs} } OPTIONAL,
	...
}

InterfacesToTrace-Item-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}

InterferenceOverloadIndication ::= OCTET STRING  -- FFS

-- J
-- K
-- L

Label ::= INTEGER (1..256)

LAC					::= OCTET STRING (SIZE (2)) --(EXCEPT ('0000'H|'FFFE'H))

LastVisitedCell-Item ::= SEQUENCE {
	global-Cell-ID					CGI,
	cellType						CellType,
	time-UE-StayedInCell			Time-UE-StayedInCell	OPTIONAL,
	iE-Extensions					ProtocolExtensionContainer { {LastVisitedCell-Item-ExtIEs} } OPTIONAL,
	...
}

LastVisitedCell-Item-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}


-- M

MME-Group-ID	::= OCTET STRING (SIZE (2))

MME-Code		::= OCTET STRING (SIZE (1))

-- N


-- O
-- P

PDCP-SN ::= INTEGER (0..4095)  

PhyCID ::= OCTET STRING


PLMN-Identity ::= OCTET STRING (SIZE(3))

-- Q
-- R

RB-type ::= INTEGER
-- Editors note: FFS To be replaced by other QCI definition, ENUMERATED??

ReceiveStatusofULPDCPSDUs ::= BIT STRING (SIZE(256)) 

RRC-Context ::= OCTET STRING

-- S

SAE-Bearer-BitRate ::= INTEGER (0..210000000000)

SAE-BearerLevel-QoS-Parameters ::= SEQUENCE {
	label				Label,
	allocationAndRetentionPriority	AllocationAndRetentionPriority,  --FFS
	sAE-BearerType			SAE-BearerType,
	...
}


SAE-BearerType ::= CHOICE {
	sAE-GBR-bearer		SAE-GBR-Bearer,
	sAE-non-GBR-bearer		SAE-Non-GBR-Bearer,
	...
}

SAE-GBR-Bearer ::= SEQUENCE {
	sAE-Bearer-MaximumBitrateDL			SAE-Bearer-BitRate,
	sAE-Bearer-MaximumBitrateUL			SAE-Bearer-BitRate,
	sAE-Bearer-GuaranteedBitrateDL		SAE-Bearer-BitRate,
	sAE-Bearer-GuaranteedBitrateUL		SAE-Bearer-BitRate,
	iE-Extensions						ProtocolExtensionContainer { {SAE-GBR-Bearer-Parameters-ExtIEs} } OPTIONAL,
	...
}

SAE-GBR-Bearer-Parameters-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}


SAE-Non-GBR-Bearer ::= SEQUENCE {
	sAE-non-GBR-Bearer-Type			SAE-Non-GBR-Bearer-Type,
	iE-Extensions						ProtocolExtensionContainer { {SAE-non-GBR-Bearer-Parameters-ExtIEs} } OPTIONAL,
	...
}

SAE-non-GBR-Bearer-Parameters-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}

SAE-Non-GBR-Bearer-Type ::= ENUMERATED {
	non-GBR-Bearer,
	...
}


ServedCells		::= SEQUENCE (SIZE (1..maxCellineNB)) OF ServedCell-Information


ServedCell-Information ::= SEQUENCE {
	phyCID				PhyCID,
	cellId				CellId,
	tAI					TAI,
	broadcastPLMNs		BroadcastPLMNs-Item,
	frequency			Frequency,
	iE-Extensions		ProtocolExtensionContainer { {ServedCell-Information-ExtIEs} } OPTIONAL,
	...
}

ServedCell-Information-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}


-- T

TAI ::= OCTET STRING 	-- FFS

TargeteNBtoSource-eNBTransparentContainer	::= OCTET STRING

Time-UE-StayedInCell ::= INTEGER

TimeToWait ::= OCTET STRING


TraceActivation ::= SEQUENCE {
	traceReference					TraceReference,
	interfacesToTrace				InterfacesToTrace,
	iE-Extensions					ProtocolExtensionContainer { {TraceActivation-ExtIEs} } OPTIONAL,
	...
}

TraceActivation-ExtIEs X2AP-PROTOCOL-EXTENSION ::= {
	...
}



TraceDepth 		::= ENUMERATED { 
	minimum,
	medium,
	maximum,
	vendorMinimum,
	vendorMedium,
	vendorMaximum,
	...
}

TraceInterface		::= ENUMERATED { 
	s1,
	x2, 
	uu,
	...
}

TraceReference					::= OCTET STRING (SIZE (3))


TransportLayerAddress			::= BIT STRING (SIZE(1..160, ...))

TypeOfError ::= ENUMERATED {
	not-understood,
	missing,
	...
}


-- U

UE-HistoryInformation ::= SEQUENCE (SIZE(1..maxnoofCells)) OF LastVisitedCell-Item


UE-S1AP-ID					::= INTEGER (0..4095) -- Value FFS

UE-X2AP-ID					::= INTEGER (0..4095) -- Value FFS




-- V
-- W
-- X
-- Y
-- Z

END
