#!/usr/bin/env python

# install the pidl modules
bld.INSTALL_FILES(bld.env.PERL_LIB_INSTALL_DIR,
                  '''
                  Parse/Pidl.pm
                  Parse/Pidl/Samba4.pm
                  Parse/Pidl/CUtil.pm
                  Parse/Pidl/Expr.pm
                  Parse/Pidl/Wireshark/Conformance.pm
                  Parse/Pidl/Wireshark/NDR.pm
                  Parse/Pidl/ODL.pm
                  Parse/Pidl/Dump.pm
                  Parse/Pidl/Util.pm
                  Parse/Pidl/Samba4/Header.pm
                  Parse/Pidl/Samba4/COM/Header.pm
                  Parse/Pidl/Samba4/COM/Proxy.pm
                  Parse/Pidl/Samba4/COM/Stub.pm
                  Parse/Pidl/Samba4/TDR.pm
                  Parse/Pidl/Samba4/NDR/Server.pm
                  Parse/Pidl/Samba4/NDR/Client.pm
                  Parse/Pidl/Samba4/NDR/Parser.pm
                  Parse/Pidl/Samba4/Python.pm
                  Parse/Pidl/Samba4/Template.pm
                  Parse/Pidl/IDL.pm
                  Parse/Pidl/Typelist.pm
                  Parse/Pidl/Samba3/ClientNDR.pm
                  Parse/Pidl/Samba3/ServerNDR.pm
                  Parse/Pidl/Compat.pm
                  Parse/Pidl/NDR.pm
                  ''',
                  flat=False)

if not bld.CONFIG_SET('USING_SYSTEM_PARSE_YAPP_DRIVER'):
    bld.INSTALL_FILES(bld.env.PERL_LIB_INSTALL_DIR,
                      'Parse/Yapp/Driver.pm',
                      flat=False)
