#
# Wireshark tests
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
"""Core NVMe dissector (packet-nvme.c) regression tests.

These tests are a *characterization baseline* for the admin-queue opcode
decode in dissect_nvme_cmd().  MR4 relocates that switch out of
dissect_nvme_cmd() into a shared nvme_dissect_admin_sqe_cdws() helper so the
NVMe-MI Admin dissector can reuse it; the move must be output-preserving for
the existing NVMe transports.  This suite locks the pre-refactor decode of a
synthetic NVMe/TCP capture so any drift introduced by the relocation fails
loudly.

Capture (generated by tools/gen-nvme-tcp-test-capture.py):

  nvme-tcp-admin.pcapng  (5 frames)
    One NVMe/TCP connection carrying five Admin CapsuleCommand PDUs, one per
    arm of the admin-queue opcode switch:
      F1 Identify (06h) CNS=01h, F2 Get Log Page (02h) LID=02h,
      F3 Set Features (09h) FID=02h, F4 Get Features (0Ah) FID=04h,
      F5 Format NVM (80h) -> CDW10 decoded (Figure 193).

Only the request side is asserted: MR4 moves only the request-side switch, so
that is the entire regression surface.  Format NVM (F5) now has its own CDW10
decoder in the shared switch, so its command dword surfaces under
nvme.cmd.format_nvm.dword10 for the NVMe transports too; the opcode *name* is
not asserted here.
"""

# The tshark_fields fixture this suite drives is the standard dissector-test
# invocation and lives in test/conftest.py.


class TestNvmeCoreAdmin:
    """Baseline decode of the admin-queue opcode switch over NVMe/TCP."""

    CAPTURE = 'nvme-tcp-admin.pcapng'

    def test_frame_count(self, tshark_fields):
        out = tshark_fields(self.CAPTURE)
        assert out.split() == ['1', '2', '3', '4', '5']

    def test_admin_opcodes(self, tshark_fields):
        """Every frame is an admin-queue command with the expected opcode."""
        out = tshark_fields(self.CAPTURE, separator='|',
                            fields=['frame.number', 'nvme.cmd.opc'])
        assert out.strip().splitlines() == [
            '1|0x06',
            '2|0x02',
            '3|0x09',
            '4|0x0a',
            '5|0x80',
        ]

    def test_cdw10_decode_per_opcode(self, tshark_fields):
        """The per-opcode CDW10 decode the switch produces -- the exact output
        the MR4 relocation must preserve byte-for-byte."""
        fields = [
            'frame.number',
            'nvme.cmd.identify.dword10.cns',
            'nvme.cmd.identify.dword10.cntid',
            'nvme.cmd.get_logpage.dword10.id',
            'nvme.cmd.set_features.dword10.fid',
            'nvme.cmd.get_features.dword10.fid',
            'nvme.cmd.format_nvm.dword10',
            'nvme.cmd.dword10',
        ]
        out = tshark_fields(self.CAPTURE, fields=fields, separator='|')
        assert out.strip().splitlines() == [
            '1|0x00000001|0x00000000|||||',  # Identify: CNS=Controller, CNTID=0
            '2|||2||||',                      # Get Log Page: LID=2 (SMART)
            '3||||0x00000002|||',            # Set Features: FID=2 (Power Mgmt)
            '4|||||0x00000004||',            # Get Features: FID=4 (Temp Thr.)
            '5||||||0x000000ab|',            # Format NVM: CDW10 now decoded
        ]

    def test_colinfo_named_opcodes(self, tshark_fields):
        """COL_INFO carries the opcode name plus the CNS / log-page detail that
        the switch appends (Identify and Get Log Page arms).  F5's name is
        omitted -- MR4 changes it by extending aq_opc_tbl."""
        out = tshark_fields(self.CAPTURE, dfilter='frame.number <= 4',
                            fields=['frame.number', '_ws.col.info'],
                            separator='|')
        assert out.strip().splitlines() == [
            '1|NVMe Identify Controller',
            '2|NVMe Get Log Page SMART/Health Information',
            '3|NVMe Set Features',
            '4|NVMe Get Features',
        ]
