#
# $Id$
#

include ..\..\config.nmake

############### no need to modify below this line #########

CFLAGS=/DHAVE_CONFIG_H /I../.. /I../../wiretap $(GLIB_CFLAGS) \
	/I$(PCAP_DIR)\include -D_U_="" $(LOCAL_CFLAGS)

OBJECTS=packet-rlm.obj 

rlm.dll rlm.exp rlm.lib : $(OBJECTS) ..\plugin_api.obj
	link -dll /out:rlm.dll $(OBJECTS) ..\plugin_api.obj \
	$(GLIB_LIBS)

clean:
	rm -f $(OBJECTS) rlm.dll rlm.exp rlm.lib $(PDB_FILE)

distclean: clean
