#!/bin/sh
#
# $Id$
#
# Make-faq - Creates a plain text version of the Wireshark FAQ
#	from http://www.wireshark.org/faq.html

rm -f FAQ
cat >FAQ <<EOF

   The Wireshark FAQ

   Note: This is just an ASCII snapshot of the faq and may not be up to
         date. Please go to http://www.wireshark.org/faq.html for the up
         to date version. The version of this snapshot can be found at
         the end of this document.

   INDEX

EOF

lynx -dump -nolist "http://www.wireshark.org/faq_plain.html" | \
	sed -e '1,/^Index/d' >>FAQ

echo
echo "Now verfiy everything is OK and copy FAQ to help/faq.txt"
echo "To verify run: diff -u help/faq.txt FAQ"
echo

exit 0
