#!/bin/sh

#
# Remove the Wireshark paths.d and manpaths.d entries.
#

rm -f /private/etc/paths.d/Wireshark
rm -f /private/etc/manpaths.d/Wireshark

# https://gitlab.com/wireshark/wireshark/-/issues/18734
pkgutil --forget org.wireshark.path_helper.pkg
