#
# $Id: Makefile.nmake,v 1.2 2003/11/06 09:05:10 guy Exp $
#

include ..\..\config.nmake

############### no need to modify below this line #########

CFLAGS=/DHAVE_CONFIG_H /I../.. /I../../wiretap $(GLIB_CFLAGS) \
	/I$(PCAP_DIR)\include -D_U_="" $(LOCAL_CFLAGS)

OBJECTS=packet-acn.obj 

acn.dll acn.exp acn.lib : $(OBJECTS) ..\plugin_api.obj
	link -dll /out:acn.dll $(OBJECTS) ..\plugin_api.obj \
	$(GLIB_LIBS)

clean:
	rm -f $(OBJECTS) acn.dll acn.exp acn.lib $(PDB_FILE)

distclean: clean
