== Introduction

This directory contains a set of resources for the Wireshark suite of
applications. Of particular note for people creating packages for
distribution are the files wireshark.ico, wiresharkdoc.ico, wsicon*.png,
and WiresharkDoc-*.png in the icons directory.

File descriptions:

wsicon16.png ... wsicon1024.png::
Wireshark application icons in various sizes

wsiconcap16.png ... wsiconcap1024.png::
“Capture in progress” application icon in various sizes

wsiconinst16.png ... wsiconinst1024.png::
Wireshark installer icons in various sizes.

WiresharkDoc-16.png ... WiresharkDoc-256.png::
Capture document icon in various sizes.

wireshark.ico::
Windows application icon file with 16x16, 24x24 32x32, 48x48, and 256x256 pixel images.

wiresharkdoc.ico::
Windows document icon file with 16 and 32 pixel 3D logo icons, high and low color.

stratoshark-app-icon.png::
Stratoshark application icon base image.

stratoshark-capture-icon.png::
Stratoshark capture icon base image.

ssicon16.png ... ssicon256.png::
Stratoshark application icons in various sizes.

stratoshark.ico::
Windows application icon file with 16x16, 32x32, 48x48, and 256x256 pixel images.

*.rc.in::
MSVC++ resource templates

stock_icons::
Various stock icons. Names _mostly_ conform to the freedesktop.org
https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html[Icon Naming Specification].
For example, the INS specifies “list-add” and “list-remove”. and we've added “list-copy”, “list-move-up“, “list-move-down”, and “list-clear”.

historic::
Old assets that should no longer be used.

The modern macOS Wireshark application icon was created by Aaron Null.
The classic Wireshark application icon, document icon, and several toolbar icons were created by Elliott Aldrich.
The Stratoshark application and capture icons were created by Travis Andersen.
The list-add and list-remove images were created by Peter Hosey and released under CC-PD.
The list-clear images were created by Freepik, http://www.freepik.com from https://www.flaticon.com.

The following projects provide icons which are a) nicely drawn and b) released under a compatible license and c) actively developed (as of October 2020) which might want to use in the future:

Bootstrap Icons: https://github.com/twbs/icons

Ionicons: https://github.com/ionic-team/ionicons

Mono Icons: https://github.com/mono-company/mono-icons

Tabler Icons: https://github.com/tabler/tabler-icons

Fluent UI System Icons: https://github.com/microsoft/fluentui-system-icons

Hero Icons: https://heroicons.com/

== Links

Microsoft: https://learn.microsoft.com/en-us/windows/apps/design/style/iconography/app-icon-construction[Construct your Windows app's icon]

Apple: https://developer.apple.com/design/human-interface-guidelines/app-icons[App icons]

GNOME: https://developer.gnome.org/hig/guidelines/app-icons.html[App Icons]
