## Makefile for building wireshark.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#

TOOLS_DIR=..\tools
include ..\config.nmake

############### no need to modify below this line #########

all: faq.txt

faq.txt: faq.py
	$(PYTHON) faq.py | $(HTML2TXT) > $@

clean:
	rm -rf faq.txt

distclean: clean

maintainer-clean: distclean

