## Makefile for building ethereal.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#
# $Id: Makefile.nmake,v 1.2 2003/12/22 08:07:13 ulfl Exp $

include ..\config.nmake

############### no need to modify below this line #########

clean:

distclean: clean
