## Makefile for building wireshark.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#
# $Id$

include ..\config.nmake

############### no need to modify below this line #########

clean:

distclean: clean

maintainer-clean: distclean
