#
WSUG_FILES =	\
	wsug_src/WSUG_app_files.xml		\
	wsug_src/WSUG_app_howitworks.xml	\
	wsug_src/WSUG_app_messages.xml		\
	wsug_src/WSUG_app_protocols.xml		\
	wsug_src/WSUG_app_tools.xml		\
	wsug_src/WSUG_chapter_advanced.xml	\
	wsug_src/WSUG_chapter_build_install.xml	\
	wsug_src/WSUG_chapter_capture.xml	\
	wsug_src/WSUG_chapter_customize.xml	\
	wsug_src/WSUG_chapter_introduction.xml	\
	wsug_src/WSUG_chapter_io.xml		\
	wsug_src/WSUG_chapter_statistics.xml	\
	wsug_src/WSUG_chapter_telephony.xml	\
	wsug_src/WSUG_chapter_troubleshoot.xml	\
	wsug_src/WSUG_chapter_use.xml		\
	wsug_src/WSUG_chapter_work.xml		\
	wsug_src/WSUG_meta_info.xml		\
	wsug_src/WSUG_preface.xml		\
	wsluarm.xml				\
	ws.css

WSUG_GRAPHICS =	\
	wsug_graphics/ws-analyze-menu.png		\
	wsug_graphics/ws-bytes-pane-tabs.png		\
	wsug_graphics/ws-bytes-pane.png			\
	wsug_graphics/ws-capture-info.png		\
	wsug_graphics/ws-capture-interfaces.png		\
	wsug_graphics/ws-capture-interface-details.png		\
	wsug_graphics/ws-capture-interfaces-win32.png	\
	wsug_graphics/ws-capture-menu.png		\
	wsug_graphics/ws-capture-options.png		\
	wsug_graphics/ws-capture-options-remote-capture.png	\
	wsug_graphics/ws-capture-options-remote-interface.png	\
	wsug_graphics/ws-capture-options-remote-settings.png	\
	wsug_graphics/ws-capture-preferences.png	\
	wsug_graphics/ws-choose-color-rule.png		\
	wsug_graphics/ws-coloring-fields.png		\
	wsug_graphics/ws-coloring-rules-dialog.png	\
	wsug_graphics/ws-column-header-popup-menu.png	\
	wsug_graphics/ws-decode-as-show.png		\
	wsug_graphics/ws-decode-as.png			\
	wsug_graphics/ws-details-pane-popup-menu.png	\
	wsug_graphics/ws-details-pane.png		\
	wsug_graphics/ws-display-filter-tcp.png		\
	wsug_graphics/ws-edit-color-rule-dialog.png	\
	wsug_graphics/ws-edit-menu.png			\
	wsug_graphics/ws-enabled-protocols.png		\
	wsug_graphics/ws-expert-colored-tree.png	\
	wsug_graphics/ws-expert-column.png		\
	wsug_graphics/ws-expert-infos.png		\
	wsug_graphics/ws-export-objects.png		\
	wsug_graphics/ws-export-pdml.png		\
	wsug_graphics/ws-export-plain.png		\
	wsug_graphics/ws-export-ps.png			\
	wsug_graphics/ws-export-psml.png		\
	wsug_graphics/ws-export-selected.png		\
	wsug_graphics/ws-file-import.png			\
	wsug_graphics/ws-file-menu.png			\
	wsug_graphics/ws-file-set-dialog.png		\
	wsug_graphics/ws-filter-add-expression.png	\
	wsug_graphics/ws-filter-toolbar.png		\
	wsug_graphics/ws-filters.png			\
	wsug_graphics/ws-find-packet.png		\
	wsug_graphics/ws-follow-stream.png		\
	wsug_graphics/ws-go-menu.png			\
	wsug_graphics/ws-goto-packet.png		\
	wsug_graphics/ws-gui-colors-preferences.png	\
	wsug_graphics/ws-gui-columns-preferences.png	\
	wsug_graphics/ws-gui-config-profiles.png	\
	wsug_graphics/ws-gui-font-preferences.png	\
	wsug_graphics/ws-gui-interface-options.png	\
	wsug_graphics/ws-gui-layout-preferences.png	\
	wsug_graphics/ws-gui-preferences.png		\
	wsug_graphics/ws-help-menu.png			\
	wsug_graphics/ws-internals-menu.png			\
	wsug_graphics/ws-list-pane.png			\
	wsug_graphics/ws-logo.png			\
	wsug_graphics/ws-main-toolbar.png		\
	wsug_graphics/ws-main.png			\
	wsug_graphics/ws-menu.png			\
	wsug_graphics/ws-merge-gtk20.png		\
	wsug_graphics/ws-merge-gtk24.png		\
	wsug_graphics/ws-merge-win32.png		\
	wsug_graphics/ws-nameresolution-preferences.png	\
	wsug_graphics/ws-open-gtk20.png			\
	wsug_graphics/ws-open-gtk24.png			\
	wsug_graphics/ws-open-win32.png			\
	wsug_graphics/ws-packet-format.png		\
	wsug_graphics/ws-packet-pane-popup-menu.png	\
	wsug_graphics/ws-packet-range.png		\
	wsug_graphics/ws-packet-selected.png		\
	wsug_graphics/ws-packet-sep-win.png		\
	wsug_graphics/ws-print.png			\
	wsug_graphics/ws-printing-preferences.png	\
	wsug_graphics/ws-save-as-gtk20.png		\
	wsug_graphics/ws-save-as-gtk24.png		\
	wsug_graphics/ws-save-as-win32.png		\
	wsug_graphics/ws-statistics-menu.png		\
	wsug_graphics/ws-stats-compare.png		\
	wsug_graphics/ws-stats-conversations.png	\
	wsug_graphics/ws-stats-endpoints.png		\
	wsug_graphics/ws-stats-hierarchy.png		\
	wsug_graphics/ws-stats-iographs.png		\
	wsug_graphics/ws-stats-srt-dcerpc-filter.png	\
	wsug_graphics/ws-stats-srt-dcerpc.png		\
	wsug_graphics/ws-stats-summary.png		\
	wsug_graphics/ws-stats-lte-mac-traffic.png		\
	wsug_graphics/ws-stats-lte-rlc-traffic.png		\
	wsug_graphics/ws-stats-wlan-traffic.png		\
	wsug_graphics/ws-statusbar-empty.png		\
	wsug_graphics/ws-statusbar-filter.png		\
	wsug_graphics/ws-statusbar-loaded.png		\
	wsug_graphics/ws-statusbar-profile.png		\
	wsug_graphics/ws-statusbar-selected.png		\
	wsug_graphics/ws-tel-rtpstream-analysis.png		\
	wsug_graphics/ws-telephony-menu.png		\
	wsug_graphics/ws-tools-menu.png	\
	wsug_graphics/ws-time-reference.png		\
	wsug_graphics/ws-view-menu.png			\
	wsug_graphics/note.png				\
	wsug_graphics/tip.png				\
	wsug_graphics/warning.png				\
	wsug_graphics/toolbar/autoscroll_24.png			\
	wsug_graphics/toolbar/capture_filter_24.png		\
	wsug_graphics/toolbar/capture_interfaces_24.png 	\
	wsug_graphics/toolbar/capture_options_24.png	 	\
	wsug_graphics/toolbar/capture_restart_24.png 		\
	wsug_graphics/toolbar/capture_start_24.png 		\
	wsug_graphics/toolbar/capture_stop_24.png 		\
	wsug_graphics/toolbar/colorize_24.png			\
	wsug_graphics/toolbar/display_filter_24.png		\
	wsug_graphics/toolbar/resize_columns_24.png		\
	wsug_graphics/toolbar/stock_add_24.png			\
	wsug_graphics/toolbar/stock_apply_20.png		\
	wsug_graphics/toolbar/stock_bottom_24.png		\
	wsug_graphics/toolbar/stock_clear_24.png		\
	wsug_graphics/toolbar/stock_close_24.png		\
	wsug_graphics/toolbar/stock_colorselector_24.png	\
	wsug_graphics/toolbar/stock_help_24.png			\
	wsug_graphics/toolbar/stock_jump_to_24.png		\
	wsug_graphics/toolbar/stock_left_arrow_24.png		\
	wsug_graphics/toolbar/stock_open_24.png			\
	wsug_graphics/toolbar/stock_preferences_24.png		\
	wsug_graphics/toolbar/stock_print_24.png		\
	wsug_graphics/toolbar/stock_properties_24.png		\
	wsug_graphics/toolbar/stock_refresh_24.png		\
	wsug_graphics/toolbar/stock_right_arrow_24.png		\
	wsug_graphics/toolbar/stock_save_24.png			\
	wsug_graphics/toolbar/stock_save_as_24.png		\
	wsug_graphics/toolbar/stock_search_24.png		\
	wsug_graphics/toolbar/stock_stop_24.png			\
	wsug_graphics/toolbar/stock_top_24.png			\
	wsug_graphics/toolbar/stock_zoom_1_24.png		\
	wsug_graphics/toolbar/stock_zoom_in_24.png		\
	wsug_graphics/toolbar/stock_zoom_out_24.png

WSDG_FILES =	\
	wsdg_src/WSDG_chapter_build_intro.asciidoc	\
	wsdg_src/WSDG_chapter_capture.asciidoc		\
	wsdg_src/WSDG_chapter_dissection.asciidoc	\
	wsdg_src/WSDG_chapter_env_intro.asciidoc	\
	wsdg_src/WSDG_chapter_libraries.asciidoc	\
	wsdg_src/WSDG_chapter_quick_setup.asciidoc	\
	wsdg_src/WSDG_chapter_sources.asciidoc		\
	wsdg_src/WSDG_chapter_tools.asciidoc		\
	wsdg_src/WSDG_chapter_userinterface.asciidoc	\
	wsdg_src/WSDG_chapter_works.asciidoc		\
	wsdg_src/WSDG_preface.asciidoc			\
	ws.css

WSDG_GENERATED_SOURCE = \
	developer-guide.xml

WSDG_GRAPHICS =	\
	wsdg_graphics/ws-capture-sync.dia	\
	wsdg_graphics/ws-capture-sync.png	\
	wsdg_graphics/ws-capture_internals.dia	\
	wsdg_graphics/ws-capture_internals.png	\
	wsdg_graphics/ws-function-blocks.dia	\
	wsdg_graphics/ws-function-blocks.png	\
	wsdg_graphics/ws-logo.png		\
	wsdg_graphics/note.png			\
	wsdg_graphics/tip.png			\
	wsdg_graphics/warning.png		\
	wsdg_graphics/toolbar/dummy.dummy

# user-guide.xml must be first in the list (to match $<)
WSUG_SOURCE =	\
	user-guide.xml		\
	git_version.xml		\
	GPL_appendix.xml	\
	custom_layer_pdf.xsl	\
	Makefile.common		\
	$(WSUG_FILES)		\
	$(WSUG_GRAPHICS)

WSDG_DIST =	\
	developer-guide.asciidoc	\
	GPL_appendix.asciidoc	\
	custom_layer_pdf.xsl	\
	Makefile.common		\
	$(WSDG_FILES)		\
	$(WSDG_GRAPHICS)

# developer-guide.xml must be first in the list (to match $<)
WSDG_SOURCE = $(WSDG_GENERATED_SOURCE) $(WSDG_DIST)

RELEASE_NOTES_SOURCE = \
	release-notes.asciidoc	\
	Makefile.common		\
	asciidoc.conf

CLEANFILES =	\
	*.chm			\
	*.fo			\
	*.hhc			\
	*.hhp			\
	*.pdf			\
	*.validated		\
	$(WSDG_GENERATED_SOURCE) \
	wsdg_chm		\
	wsdg_html.zip		\
	wsdg_html_chunked.zip	\
	wsug_chm		\
	wsug_html.zip		\
	wsug_html_chunked.zip	\
	htmlhelp.*		\
	release_notes_chm	\
	release-notes.html	\
	release-notes.txt	\
	git_version.xml		\
	user-guide.zip		\
	wsluarm

CLEANDIRS =	\
	wsdg_html		\
	wsdg_html_chunked	\
	wsug_html		\
	wsug_html_chunked	\
	wsluarm_src

WSLUA_MODULES = \
	$(top_srcdir)/epan/wslua/wslua_dumper.c \
	$(top_srcdir)/epan/wslua/wslua_field.c \
	$(top_srcdir)/epan/wslua/wslua_gui.c \
	$(top_srcdir)/epan/wslua/wslua_listener.c \
	$(top_srcdir)/epan/wslua/wslua_pinfo.c \
	$(top_srcdir)/epan/wslua/wslua_proto.c \
	$(top_srcdir)/epan/wslua/wslua_int64.c \
	$(top_srcdir)/epan/wslua/wslua_struct.c \
	$(top_srcdir)/epan/wslua/wslua_tree.c \
	$(top_srcdir)/epan/wslua/wslua_tvb.c \
	$(top_srcdir)/epan/wslua/wslua_file.c \
	$(top_srcdir)/epan/wslua/wslua_dir.c \
	$(top_srcdir)/epan/wslua/wslua_util.c
