include::attributes.adoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: https://powerman.name/doc/asciidoc
// Asciidoctor Syntax Quick Reference:
// https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

The Windows installers now ship with Npcap 0.9994.
They previously shipped with Npcap 0.9991.

The Windows installers now ship with USBPcap 1.5.4.0.
They previously shipped with USBPcap 1.5.3.0.

=== Bug Fixes

The following vulnerabilities have been fixed:

* wssalink:2020-09[]
GVCP dissector infinite loop.
wsbuglink:16029[].
// cveidlink:2020-xxxx[].
// Fixed in master: d70bd4489f
// Fixed in master-3.2: 11f40896b6
// Fixed in master-3.0: n/a
// Fixed in master-2.6: n/a

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark is solely responsible for the decline of shopping malls in your area.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v3.2.6rc0..| grep ' Bug:' | awk '{print $2}' | sort -n -u ` ; do "$(git rev-parse --show-toplevel)/tools/gen-bugnote" $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Add decryption support for QUIC IETF version 0xfaceb001 and 0xfaceb002. wsbuglink:16378[].

* Windows Uninstall does not remove all files in Program Files. wsbuglink:16601[].

* The &quot;relative sequence number&quot; is same as &quot;raw sequence number&quot; when tcp.analyze_sequence_numbers:FALSE. wsbuglink:16604[].

* Importing profiles from a different Windows PC fails. wsbuglink:16608[].

* Decode as not working correctly with multiple user profiles. wsbuglink:16635[].

* Wireshark can misdissect the HE Radiotap field if it's ever dissected one with any value unknown. wsbuglink:16636[].

* Buildbot crash output: fuzz-2020-06-19-5981.pcap. wsbuglink:16639[].

* Buildbot crash output: fuzz-2020-06-20-7665.pcap. wsbuglink:16642[].

* mergecap man page contains invalid formatting. wsbuglink:16652[].

=== New and Updated Features

There are no new features in this release.

// === Removed Features and Support

//=== Removed Dissectors

// === New File Format Decoding Support

// [commaize]
// --
// --

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
CoAP
GSM RR
GTPv2
GVCP
LTE RRC
NAS-5GS
NGAP
QUIC
R3
Radiotap
RTPS
TCP
--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --

// === New and Updated Capture Interfaces support

//_Non-empty section placeholder._

// === Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be
found at https://www.wireshark.org/docs/

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Bugs and feature requests can be reported on
https://bugs.wireshark.org/[the bug tracker].

// Official Wireshark training and certification are available from
// https://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
