include::attributes.adoc[]
:stylesheet: ws.css
:linkcss:
:copycss: {stylesheet}

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

__We do not ship official 32-bit Windows packages for Wireshark 4.0 and later__.
If you need to use Wireshark on that platform, we recommend using the latest 3.6 release.
wsbuglink:17779[]

// * The Windows installers now ship with Qt 5.12.2.
// They previously shipped with Qt 6.2.3.

If you’re running Wireshark on macOS and upgraded to macOS 13 from an earlier version, you might have to open and run the “Uninstall ChmodBPF” package, then open and run “Install ChmodBPF” in order to reset the ChmodBPF Launch Daemon.
wsbuglink:18734[].

=== Bug Fixes

The following vulnerabilities have been fixed:

* wssalink:2023-28[]
SSH dissector crash.
wsbuglink:19369[].
// cveidlink:2023-xxx[].
// Fixed in master: 348c9991f9
// Fixed in release-4.2: 9bb2f610ed
// Fixed in release-4.0: 28ad7bdb67
// Fixed in release-3.6: n/a
// CVSS AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
// CWE-125, CWE-835

// * Fuzz job crash output: fuzz-2023-10-02-7109.pcap. wsbuglink:19369[].

* wssalink:2023-29[]
NetScreen file parser crash.
wsbuglink:19404[].
// cveidlink:2023-xxx[].
// Fixed in master: 3be1c99180
// Fixed in release-4.2: 95c12710ef
// Fixed in release-4.0: 160d1e454a
// Fixed in release-3.6: 197e96f053
// CVSS AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H
// CWE-120

// * NetScreen File Parsing Heap-based Buffer Overflow. wsbuglink:19404[].

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark insists on subscribing to two dozen streaming services but only watches three.

* First ZigBee APS packet is not decrypted. wsbuglink:16507[].
* Problem with decoding OpenFlow actions in OFPT_FLOW_MOD message. wsbuglink:17072[].
* The "frames" method in sharkd does not consider time references and displays incorrect delta time. wsbuglink:17923[].
* Wireshark and TShark throw packet-wireguard-WARNING when running on systems with FIPS enabled. wsbuglink:18441[].
* Wireshark interprets If_fcslen option in the Interface Description Block as byte instead of bit. wsbuglink:19174[].
* Flathub's Wireshark page shows wrong version number. wsbuglink:19382[].
* OSPFv3 RI decode error. wsbuglink:19444[].
* GSM SIM READ / UPDATE BINARY command has wrong offset. wsbuglink:19472[].
// * packet-isdn-sup.c: -Wunreachable-code with Clang 17. wsbuglink:19477[].

=== New and Updated Features

There are no new or updated features in this release.

// === Removed Features and Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
// ag -A1 '(define PSNAME|proto_register_protocol[^_])' $(git diff --name-only v4.0.11.. | ag packet- | sort -u)
[commaize]
--
DHCP
GSM SIM
IEEE 1722
ISDN SUP
ISO 15765
OpenFlow v1
OSPF
SSH
TCP
TECMP
WireGuard
Wi-SUN
ZigBee
--

=== New and Updated Capture File Support

// There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
[commaize]
--
NetScreen
pcapng
--

// === New and Updated Capture Interfaces support

//_Non-empty section placeholder._

=== New File Format Decoding Support

There is no new or updated file format support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --

// === New and Updated Capture Interfaces support

//_Non-empty section placeholder._

// === Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages.
You can usually install or upgrade Wireshark using the package management system specific to that platform.
A list of third-party packages can be found on the
https://www.wireshark.org/download.html[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference files, plugins, SNMP MIBS, and RADIUS dictionaries.
These locations vary from platform to platform.
You can use menu:Help[About Wireshark,Folders] or `tshark -G folders` to find the default locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be found at
https://www.wireshark.org/docs/

Community support is available on
https://ask.wireshark.org/[Wireshark’s Q&A site]
and on the wireshark-users mailing list.
Subscription information and archives for all of Wireshark’s mailing lists can be found on
https://www.wireshark.org/lists/[the web site].

Bugs and feature requests can be reported on
https://gitlab.com/wireshark/wireshark/-/issues[the issue tracker].

You can learn protocol analysis and meet Wireshark’s developers at
https://sharkfest.wireshark.org[SharkFest].

// Official Wireshark training and certification are available from
// https://www.wiresharktraining.com/[Wireshark University].

== How You Can Help

The Wireshark Foundation helps as many people as possible understand their networks as much as possible.
You can find out more and donate at https://wiresharkfoundation.org[wiresharkfoundation.org].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
