= Wireshark wireshark-version:[] Release Notes

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

// Link templates: ws-buglink:5000[]  ws-buglink:6000[Wireshark bug]  cve-idlink:2016-7000[]

The following vulnerabilities have been fixed:

* ws-salink:2016-22[]
+
The PKTC dissector could crash.
(ws-buglink:12206[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 4cdc9ee
// Fixed in master-2.0: 99d549f
// Fixed in master-1.12: 4446971

* ws-salink:2016-23[]
+
The PKTC dissector could crash.
(ws-buglink:12242[])
//cve-idlink:2015-XXXX[]
// Fixed in master: ad09738
// Fixed in master-2.0: a7fcd61
// Fixed in master-1.12: df3d07b

* ws-salink:2016-24[]
+
The IAX2 dissector could go into an infinite loop.
(ws-buglink:12260[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 42f299b
// Fixed in master-2.0: fedd01d
// Fixed in master-1.12: 73dbc54

* ws-salink:2016-25[]
+
Wireshark and TShark could exhaust the stack.
(ws-buglink:12268[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 8dc9551
// Fixed in master-2.0: fcff256
// Fixed in master-1.12: c5a9678

* ws-salink:2016-26[]
+
The GSM CBCH dissector could crash.
(ws-buglink:12278[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 0fe522d
// Fixed in master-2.0: 363dc72
// Fixed in master-1.12: edf4950

* ws-salink:2016-28[]
+
The NCP dissector could crash.
(ws-buglink:12293[])
//cve-idlink:2015-XXXX[]
// Fixed in master: N/A
// Fixed in master-2.0: N/A
// Fixed in master-1.12: 99efcb0

The following bugs have been fixed:

//* Wireshark always manages to score tickets for Burning Man, Coachella, and
//  SXSW while you end up working double shifts. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v1.12.11rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* wlan, wlan_mgt, Length error shown for IE BSS AC Access Delay/WAPI Parameter Set (68). (ws-buglink:12223[])

* RPC/NFS incorrectly decodes as ACAP. (ws-buglink:12265[])

* Wireshark mistakenly flags CF-End packets as being Malformed. (ws-buglink:12266[])

* ASTERIX Category 48 Reserved Expansion Field. (ws-buglink:12267[])

* Dissector bug, failed assertion, proto_desegment pinfo->can_desegment. (ws-buglink:12285[])

* Malformed Packet: RTP. (ws-buglink:12339[])

* Incorrect error on MPA pdu length on iWARP packets. (ws-buglink:12348[])


Windows installers and PortableApps(R) packages are dual signed using SHA-1 and SHA-256
in order to comply with
http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx[Microsoft Authenticode policy].
Windows 7 and Windows Server 2008 R2 users should ensure that
https://support.microsoft.com/en-us/kb/3123479[update 3123479] is installed.
Windows Vista and Windows Server 2008 users should ensure that
https://support.microsoft.com/en-us/kb/2763674[hotfix 2763674] is installed.

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
ACAP
Asterix
GPRS LLC
GSM
IAX2
IEEE 802.11
INAP
iWARP MPA
Kerberos
MySQL
NCP
RTP
SMB
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
Gammu DCT3
--sort-and-group--

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
