= Wireshark wireshark-version:[] Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

* Invalid coloring rules are now disabled instead of discarded. This will
  provide forward compatibility with a coloring rule change in Wireshark 2.2.

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2016-59[]
+
AllJoyn crash.
(ws-buglink:12953[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 7dfaec9
// Fixed in master-2.2: f44fd03
// Fixed in master-2.0: a5770b6

* ws-salink:2016-60[]
+
OpenFlow crash.
(ws-buglink:13071[])
//cve-idlink:2015-XXXX[]
// Fixed in master: d1a7ed1
// Fixed in master-2.2: 51348a7
// Fixed in master-2.0: f2a7af8

* ws-salink:2016-61[]
+
DCERPC crash.
(ws-buglink:13072[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 929ad38
// Fixed in master-2.2: 3f45798
// Fixed in master-2.0: cc8e37f

* ws-salink:2016-62[]
+
DTN infinite loop.
(ws-buglink:13097[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 63776db
// Fixed in master-2.2: 14bba92
// Fixed in master-2.0: be6a10a

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2016-7000[]
//* Wireshark insists on calling you on your land line which is keeping you from abandoning it for cellular. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.0.8rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* SMPP schedule_delivery_time displayed wrong in Wireshark 2.1.0. (ws-buglink:12632[])

* Upgrading to latest version uninstalls Microsoft Visual C++ redistributable. (ws-buglink:12712[])

* smpp.message not decoded & not available for export using tshark -T fields -e smpp.message. (ws-buglink:12960[])

* CLNP dissector does not parse ER NPDU properly. (ws-buglink:12993[])

* SNMP trap bindings for NON scalar OIDs. (ws-buglink:13013[])

* BGP LS Link Protection Type TLV (1093) decoding. (ws-buglink:13021[])

* Application crash sorting column for tcp.window_size_scalefactor up and down. (ws-buglink:13023[])

* ZigBee Green Power add key during execution. (ws-buglink:13031[])

* Malformed AMPQ packets for session.expected and session.confirmed fields. (ws-buglink:13037[])

* [IS-637A] SMS - Teleservice layer parameter --> IA5 encoded text is not correctly displayed. (ws-buglink:13065[])

* Field sna.gds is is not of an FT_\{U\}INTn type. (ws-buglink:13084[])

* E212: 3 digits MNC are identified as 2 digits long if they end with a 0. (ws-buglink:13092[])

* Dissector skips DICOM command. (ws-buglink:13110[])

* Manufacturer name resolution fail. (ws-buglink:13126[])

The Windows PortableApps packages were susceptible to a
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=12724[DLL hijacking flaw].

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
AllJoyn
AMPQ
ANSI IS-637 A
BGP
CLNP
DCERPC
DICOM
DTN
E.212
OpenFlow
SMPP
SNA
SNMP
ZigBee
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

The 64-bit version of Wireshark will leak memory on Windows when the display
depth is set to 16 bits (ws-buglink:9914[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
