include::attributes.asciidoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What’s New

* The Windows installers now ship with Qt 5.9.5. Previously they shipped with Qt 5.9.4.

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2018-25[]
+
A dissector went awry.
(ws-buglink:xxxx[])
// cve-idlink:2018-xxxx[]
// Fixed in master: xxxx
// Fixed in master-2.6: xxxx
// Fixed in master-2.4: xxxx
// Fixed in master-2.2: xxxx

The following bugs have been fixed:

//* ws_buglink:5000[]
//* ws_buglink:6000[Wireshark bug]
//* cve_idlink:2014-2486[]
//* Wireshark convinced you to switch seats on the plane while neglecting to tell you that its seat was noticeably moist.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.6.1rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do ./tools/gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
--

=== New and Updated Capture File Support

//_Non-empty section placeholder._
// Add one file type per line between the -- delimiters.
[commaize]
--
--

=== New and Updated Capture Interfaces support

//_Non-empty section placeholder._
[commaize]
--
--

//=== Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

The BER dissector might infinitely loop.
(ws_buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws_buglink:1814[])

Filtering tshark captures with read filters (`-R`) no longer works.
(ws_buglink:2234[])

Application crash when changing real-time option.
(ws_buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws_buglink:4985[])

Wireshark should let you work with multiple capture files. (ws_buglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
