= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2017-03[]
+
LDSS dissector crash
(ws-buglink:13346[])
//cve-idlink:2017-XXXX[]
// Fixed in master: eeab554cf2
// Fixed in master-2.2: a1d434d9db
// Fixed in master-2.0: 4f753c1270

* ws-salink:2017-04[]
+
RTMTP dissector infinite loop
(ws-buglink:13347[])
//cve-idlink:2017-XXXX[]
// Fixed in master: ee185445f4
// Fixed in master-2.2: 2b3a0909be
// Fixed in master-2.0: n/a

* ws-salink:2017-05[]
+
WSP dissector infinite loop
(ws-buglink:13348[])
//cve-idlink:2017-XXXX[]
// Fixed in master: cfe7b85b86
// Fixed in master-2.2: b708d4e6b4
// Fixed in master-2.0: 62afef4127

* ws-salink:2017-06[]
+
STANAG 4607 file parser infinite loop
(ws-buglink:13416[])
//cve-idlink:2017-XXXX[]
// Fixed in master: c7042bedbb
// Fixed in master-2.2: 83aa52d9ba
// Fixed in master-2.0: 38b428a317

* ws-salink:2017-07[]
+
NetScaler file parser infinite loop
(ws-buglink:13429[])
//cve-idlink:2017-XXXX[]
// Fixed in master: e4dfeed2ca
// Fixed in master-2.2: d00ced1548
// Fixed in master-2.0: a998c9195f

* ws-salink:2017-08[]
+
NetScaler file parser crash
(ws-buglink:13430[])
//cve-idlink:2017-XXXX[]
// Fixed in master: 19c51d27b9, b98bb5188c
// Fixed in master-2.2: 7eb76d2975, 70184273ad
// Fixed in master-2.0: 9f3bc84b7e, 5e9cd0ab84

* ws-salink:2017-09[]
+
K12 file parser crash
(ws-buglink:13431[])
//cve-idlink:2017-XXXX[]
// Fixed in master: b019c5931c, 4bd3c4d44d
// Fixed in master-2.2: 37bbc14b05, 7d1d41ae8b
// Fixed in master-2.0: 7edc761a01, c83d7c0432

The 32-bit and 64-bit Windows installers might have been susceptible to a
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=13369[DLL hijacking flaw].

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.2.5rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Display filter textbox loses focus during live capturing. (ws-buglink:11890[])

* Wireshark crashes when saving pcaps, opening pcaps, and exporting specified packets. (ws-buglink:12036[])

* tshark stalls on FreeBSD if androiddump is present. (ws-buglink:13104[])

* UTF-8 characters in packet list column title. (ws-buglink:13342[])

* Recent capture file list should appear immediately on startup. (ws-buglink:13352[])

* editcap segfault if a packet length is shorter than ignore bytes parameter. (ws-buglink:13378[])

* dftest segfault with automated build of 2.2.5. (ws-buglink:13387[])

* UMTS MAC Dissector shows Packet size limited for BCCH payload. (ws-buglink:13392[])

* VS2010 win32 编译失败. (ws-buglink:13398[])

* EAP AKA not being decoded properly. (ws-buglink:13411[])

* Dumpcap crashes during rpcap setup. (ws-buglink:13418[])

* Crash on closing SNMP capture file if snmp credentials are present. (ws-buglink:13420[])

* GPRS-NS message PDU type displayed in octal instead of hexadecimal. (ws-buglink:13428[])

// Left off at 7d1d41ae8b
=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
--sort-and-group--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.

--sort-and-group--
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

=== Major API Changes

There are no major API changes in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
