include::attributes.asciidoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

=== Bug Fixes

// The following vulnerabilities have been fixed:

* wssalink:2020-03[]
LTE RRC dissector memory leak.
wsbuglink:16341[].
// cveidlink:2019-xxxxx[].
// Fixed in master: adeeb7f2da
// Fixed in master-3.2: 0ce952b724
// Fixed in master-3.0: 873dca931a
// Fixed in master-2.6: 086003c9d6

* wssalink:2020-04[]
WiMax DLMAP dissector crash.
wsbuglink:16368[].
// cveidlink:2019-xxxxx[].
// Fixed in master: 7ce2ca316c, 6dad599a8a
// Fixed in master-3.2: 49c6720028, 5a13c2316f
// Fixed in master-3.0: 135cf649b1, 3daba57466
// Fixed in master-2.6: 93d6b03a67, 6b98dc6370

* wssalink:2020-05[]
EAP dissector crash.
wsbuglink:16397[].
// cveidlink:2019-xxxxx[].
// Fixed in master: 8bda8642df
// Fixed in master-3.2: 79769da3b5
// Fixed in master-3.0: 924ae4d091
// Fixed in master-2.6: 9fe2de783d

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark convinced you to switch seats on the plane while neglecting to tell you that its seat was noticeably moist.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.6.16rc0..| grep ' Bug:' | awk '{print $2}' | sort -n -u ` ; do "$(git rev-parse --show-toplevel)/tools/gen-bugnote" $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Wireshark fails to build with GCC-9. wsbuglink:16319[].

* ICMP: No response if ICMP reply packet has an ICMP checksum of 0x0000. wsbuglink:16334[].

* IPv4 fragment offset value is incorrect in IPv4 header decode. wsbuglink:16344[].

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
ARTNET
EAP
ICMP
ICMPv6
IPv4
LTE RRC
RDM
WiMax DLMAP
--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --

=== New and Updated Capture Interfaces support

There is no new or updated capture file support in this release.
// [commaize]
// --
// --

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

The BER dissector might infinitely loop.
wsbuglink:1516[].

Capture filters aren't applied when capturing from named pipes.
wsbuglink:1814[].

Filtering tshark captures with read filters (`-R`) no longer works.
wsbuglink:2234[].

Application crash when changing real-time option.
wsbuglink:4035[].

Wireshark and TShark will display incorrect delta times in some cases.
wsbuglink:4985[].

Wireshark should let you work with multiple capture files. wsbuglink:10488[].

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

// Official Wireshark training and certification are available from
// http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
