= Wireshark wireshark-version:[] Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

//* ws-salink:2016-63[]
//+
//A dissector went awry.
//(ws-buglink:xxxx[])
//cve-idlink:2015-XXXX[]
// Fixed in master: xxxx
// Fixed in master-2.2: xxxx
// Fixed in master-2.0: xxxx

* Arbitrary file deletion on Windows. (ws-buglink:13217[])

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2016-7000[]
//* Wireshark insists on calling you on your land line which is keeping you from abandoning it for cellular. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.0.9rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Saving all exported objects (SMB/SMB2) results in out of physical memory. (ws-buglink:11133[])

* Export HTTP Objects - Single file shows as multiple files in 2.0.2. (ws-buglink:12230[])

* Dicom list of tags in element of VR=AT not properly decoded. (ws-buglink:13077[])

* Malformed Packet: BGP Update (withdraw) message. (ws-buglink:13146[])

* GTP: "Create PDP Context response" message shows back-off timer as malformed when included in the response. (ws-buglink:13153[])

* ICMP dissector fails to properly detect timestamps. (ws-buglink:13161[])

* RLC misdissection. (ws-buglink:13162[])

* Text2pcap on windows produces corrupt output when writing the capture file to the standard output. (ws-buglink:13165[])

* TShark doesn't respect protocols.display_hidden_proto_items setting. (ws-buglink:13192[])

* RPC/RDMA dissector should exit when frame is not RPC-over-RDMA. (ws-buglink:13195[])

* Some RPC-over-RDMA frames are not recognized as RPC-over-RDMA. (ws-buglink:13196[])

* Wireshark shows "MS Video Source Request" in a RTCP packet as "Malformed". (ws-buglink:13212[])

// Left off at 21469e1

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
BGP
BTLE
DICOM
GTP
ICMP
RPC over RDMA
RTCP
SDP
SMB
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

The 64-bit version of Wireshark will leak memory on Windows when the display
depth is set to 16 bits (ws-buglink:9914[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
