= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2018-15[]
+
The MP4 dissector could crash.
(ws-buglink:13777[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 620f69a74b
// Fixed in master-2.4: 2113179835
// Fixed in master-2.2: f927769fdf

* ws-salink:2018-16[]
+
The ADB dissector could crash.
(ws-buglink:14460[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 1653ea5fce
// Fixed in master-2.4: 23c0a41442
// Fixed in master-2.2: 0290a62be0

* ws-salink:2018-17[]
+
The IEEE 802.15.4 dissector could crash.
(ws-buglink:14468[])
// cve-idlink:2018-xxxx[]
// Fixed in master: dd21b8130c
// Fixed in master-2.4: b87aa0326c
// Fixed in master-2.2: 14d6f717d8

* ws-salink:2018-18[]
+
The NBAP dissector could crash.
(ws-buglink:14471[])
// cve-idlink:2018-xxxx[]
// Fixed in master: cde7cc54a3
// Fixed in master-2.4: 1c9adc63c2
// Fixed in master-2.2: xxxx

* ws-salink:2018-19[]
+
The VLAN dissector could crash.
(ws-buglink:14469[])
// cve-idlink:2018-xxxx[]
// Fixed in master: b434e0a03b
// Fixed in master-2.4: 7929700033
// Fixed in master-2.2: f05c3b91f9

* ws-salink:2018-20[]
+
The LWAPP dissector could crash.
(ws-buglink:14467[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 1592587e6f
// Fixed in master-2.4: 13270b1bc0
// Fixed in master-2.2: dac48f1485

* ws-salink:2018-23[]
+
The Kerberos dissector could crash.
(ws-buglink:14576[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 4adb8e9f6a
// Fixed in master-2.4: 744f56721c
// Fixed in master-2.2: 4fe65168fd

* ws-salink:2018-24[]
+
Multiple dissectors and other modules could leak memory.
The TN3270 (ws-buglink:14480[]),
ISUP (ws-buglink:14481[]),
LAPD (ws-buglink:14482[]),
SMB2 (ws-buglink:14483[]),
GIOP (ws-buglink:14484[]),
ASN.1 (ws-buglink:14485[]),
MIME multipart (ws-buglink:14486[]),
H.223 (ws-buglink:14487[]), and
PCP (ws-buglink:14488[])
dissectors were susceptible along with
Wireshark and TShark (ws-buglink:14489[]).
// cve-idlink:2018-xxxx[]
// Fixed in master: many
// Fixed in master-2.4: many
// Fixed in master-2.2: many

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.2.15rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do ./tools/gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Lua script calling Ethernet dissector runs OK in 1.12.4 but crashes in later releases. (ws-buglink:14293[])

* PEEKREMOTE dissector lacks 80mhz support, short preamble support and spatial streams encoding. (ws-buglink:14452[])

* Typo error in enumeration value of speech version identifier. (ws-buglink:14528[])

* WCCP logical error in CHECK_LENGTH_ADVANCE_OFFSET macros. (ws-buglink:14538[])

* Buildbot crash output: fuzz-2018-03-19-19114.pcap. (ws-buglink:14544[])

* alloca() used in wsutil/getopt_long.c without <alloca.h> inclusion. (ws-buglink:14552[])

* HP-UX HP ANSI C requires -Wp,-H200000 flag to compile. (ws-buglink:14554[])

* Makefile.in uses non-portable "install" command. (ws-buglink:14555[])

* HP-UX HP ANSI C doesn't support assigning {} to a variable in epan/app_mem_usage.c. (ws-buglink:14556[])

* PPP in SSTP, HDLC framing not parsed properly. (ws-buglink:14559[])

* Using the DIAMETER dictionary causes the standard input to be closed when the dictionary is read. (ws-buglink:14577[])


=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
6LoWPAN
ADB
DNS
Ethernet
IEEE 802.11
IEEE 802.11 Radiotap
IEEE 802.15.4
GIOP
GSM BSSMAP
ISUP
H.223
Kerberos
LAPD
LWAPP
MIME multipart
MP4
NBAP
PCP
PEEKREMOTE
S1AP
T.30
TN3270
SMB2
SSTP
VLAN
WCCP
WSP
--sort-and-group--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
//--sort-and-group--
//--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

=== Major API Changes

There are no major API changes in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
