include::attributes.asciidoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What’s New

=== Bug Fixes

The following vulnerabilities have been fixed:

* wssalink:2019-20[]
ASN.1 BER and related dissectors crash.
wsbuglink:15870[].
// cveidlink:2019-XXXXX[].
// Fixed in master: 45a3d0787f
// Fixed in master-3.0: 650fb1f786
// Fixed in master-2.6: 7e90aed666
// Fixed in master-2.4: 0d74e50d9a

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark convinced you to switch seats on the plane while neglecting to tell you that its seat was noticeably moist.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.6.10rc0..| grep ' Bug:' | awk '{print $2}' | sort -n -u ` ; do "$(git rev-parse --show-toplevel)/tools/gen-bugnote" $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Wireshark 2.6.3 crashes in QIcon destructor on closing the main window on Ubuntu 14.04 and 16.04. wsbuglink:15241[].

* RSL dissector bugs in presence of optional IEs. wsbuglink:15789[].

* The "Media Attribute Value" field is missed in rtcp SDP dissection (packet-sdp.c). wsbuglink:15791[].

* BTLE doesn't properly detect start fragment of L2CAP PDUs. wsbuglink:15807[].

* tshark: Display filter error message references "-d" when it should reference "-Y". wsbuglink:15825[].

* Open "protocol" preferences ... does not work for protocol in subtree. wsbuglink:15836[].

* Problems with sshdump "Error by extcap pipe: sh: sudo: command not found". wsbuglink:15845[].

* editcap won't change encapsulation type when writing pcap format. wsbuglink:15873[].


=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
ASN.1
BTLE
CUPS
DNS
DPNSS
GSM RLC/MAC
HiQnet
ISObus VT
MAC LTE
MIME multipart
MQ
RSL
SDP
SMB
TNEF
--

=== New and Updated Capture File Support

// There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
[commaize]
--
Ascend
--

=== New and Updated Capture Interfaces support

There is no new or updated capture file support in this release.
// [commaize]
// --
// --

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

The BER dissector might infinitely loop.
wsbuglink:1516[].

Capture filters aren't applied when capturing from named pipes.
wsbuglink:1814[].

Filtering tshark captures with read filters (`-R`) no longer works.
wsbuglink:2234[].

Application crash when changing real-time option.
wsbuglink:4035[].

Wireshark and TShark will display incorrect delta times in some cases.
wsbuglink:4985[].

Wireshark should let you work with multiple capture files. wsbuglink:10488[].

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
