= Wireshark 1.9.1 Release Notes

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following bugs have been fixed:

//* ws-buglink:5000
//* cve-idlink:2013-2486

=== New and Updated Features

The following features are new (or have been significantly updated)
since version 1.8:

* Wireshark on 32- and 64-bit Windows supports automatic updates.
* The packet bytes view is faster.
* You can now display a list of resolved host names in "hosts" format
within Wireshark.
* The wireless toolbar has been updated.
* Wireshark on Linux does a better job of detecting interface addition
and removal.
* It is now possible to compare two fields in a display filter (for
example: udp.srcport != udp.dstport). The two fields must be of the same
type for this to work.
* The main welcome screen and status bar now display file sizes using
strict SI prefixes instead of old-style binary prefixes.
* Capinfos now prints human-readable statistics with SI suffixes by
default.

=== New Protocol Support

No new protocols

=== Updated Protocol Support

Too many protocols have been updated to list here.

=== New and Updated Capture File Support

No new or updated capture files.

== Getting Wireshark

Wireshark source code and installation packages are available from
http://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the http://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419)

The BER dissector might infinitely loop.
(ws-buglink:1516)

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814)

Filtering tshark captures with display filters (-R) no longer works.
(ws-buglink:2234)

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Application crash when changing real-time option.
(ws-buglink:4035)

Hex pane display issue after startup.
(ws-buglink:4056)

Packet list rows are oversized.
(ws-buglink:4357)

Summary pane selected frame highlighting not maintained.
(ws-buglink:4445)

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985)

== Getting Help

Community support is available on http://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on http://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
http://www.wireshark.org/faq.html[Wireshark web site].
