= Wireshark wireshark-version:[] Release Notes
// $Id$

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed.

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* ws-salink:2013-11[]
//* cve-idlink:2013-2486[]

* ws-salink:2013-66[]
+
The SIP dissector could go into an infinite loop. Discovered by Alain Botti.
// Fixed in trunk-1.10: r53195
// Fixed in trunk-1.8: r53197
(ws-buglink:9388[])
+
Versions affected: 1.10.0 to 1.10.3, 1.8.0 to 1.8.11
//+
//cve-idlink:2013-XXXX[]

* ws-salink:2013-67[]
+
The ASN.1 PER dissector could crash. Discovered by Laurent Butti.
// Fixed in trunk-1.10: r53803
(ws-buglink:9488[])
+
Versions affected: 1.10.0 to 1.10.3, 1.8.0 to 1.8.11
//+
//cve-idlink:2013-XXXX[]

The following bugs have been fixed:

//* Wireshark will practice the jazz flute for hours on end when you're trying to sleep. (ws-buglink:0000[])

* "On-the-wire" packet lengths are limited to 65535 bytes. (ws-buglink:8808[], ws-buglink:9390)
* VoIP Graph Analysis window - some calls are black. (ws-buglink:8966[])
* Wireshark fails to decode single-line, multiple Contact: URIs in SIP responses. (ws-buglink:9031[])
* epan/follow.c - Incorrect "bytes missing in capture file" in "check_fragments" due to an unsigned int wraparound?. (ws-buglink:9112[])
* gsm_map doesn't decode MAPv3 reportSM-DeliveryStatus result. (ws-buglink:9382[])
* Incorrect NFSv4 FATTR4_SECURITY_LABEL value. (ws-buglink:9383[])
* SEL Fast Message Bug-fix for Signed 16-bit Integer Fast Meter Messages. (ws-buglink:9435[])
* DNP3 Bug Fix for Analog Data Sign Bit Handling. (ws-buglink:9442[])

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--

ASN.1 PER
DNP3
GSM MAP
NFSv4
SEL FM
SIP

--sort-and-group--

=== New and Updated Capture File Support

--sort-and-group--

.

--sort-and-group--

== Getting Wireshark

Wireshark source code and installation packages are available from
http://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the http://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Summary pane selected frame highlighting not maintained.
(ws-buglink:4445[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

== Getting Help

Community support is available on http://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on http://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
http://www.wireshark.org/faq.html[Wireshark web site].
