include::attributes.asciidoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

=== Bug Fixes

// The following vulnerabilities have been fixed:

// * wssalink:2020-10[]
// Foo dissector {crash,infinite loop}.
// wsbuglink:xxxx[].
// cveidlink:2020-xxxx[].
// Fixed in master: xxxx
// Fixed in master-3.2: xxxx
// Fixed in master-3.0: xxxx
// Fixed in master-2.6: xxxx

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark convinced you to switch seats on the plane while neglecting to tell you that its seat was noticeably moist.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.6.20rc0..| grep ' Bug:' | awk '{print $2}' | sort -n -u ` ; do "$(git rev-parse --show-toplevel)/tools/gen-bugnote" $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Dissector for ASTERIX Category 001 / 210 does not recognize bit 1 as extension. wsbuglink:16662[].

* Short IMSIs (5 digits) lead to wrong decoding+warning. wsbuglink:16676[].

* Decoding of PFCP IE 'PFD Contents' results in &quot;malformed packet&quot;. wsbuglink:16704[].

* RFH2 Header with 32 or less bytes of NameValue will not parse out that info. wsbuglink:16733[].

* CDP: Port ID TLV followed by Type 1009 TLV triggers [Malformed Packet]. wsbuglink:16742[].

* tshark crashed when processing opcda. wsbuglink:16746[].

* tshark with --export-dicom gives “Segmentation fault (core dumped)”. wsbuglink:16748[].

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
ASTERIX
BSSAP
CDP
DCERPC SPOOLSS
DCOM
DVB-S2
E.212
GSM RR
GSM SMS
IEEE 802.11
MQ
Nano
NIS+
PFCP
RTPS
TDS
TN3270
TN5250
--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --

=== New and Updated Capture Interfaces support

There is no new or updated capture file support in this release.
// [commaize]
// --
// --

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

The BER dissector might infinitely loop.
wsbuglink:1516[].

Capture filters aren't applied when capturing from named pipes.
wsbuglink:1814[].

Filtering tshark captures with read filters (`-R`) no longer works.
wsbuglink:2234[].

Application crash when changing real-time option.
wsbuglink:4035[].

Wireshark and TShark will display incorrect delta times in some cases.
wsbuglink:4985[].

Wireshark should let you work with multiple capture files. wsbuglink:10488[].

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

// Official Wireshark training and certification are available from
// http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
