include::attributes.adoc[]
:stylesheet: ws.css
:linkcss:
:copycss: {stylesheet}

== Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

__This is the last release branch with support for 32-bit Windows.__
Updates will no longer be available after May 22, 2024 for that platform.
wsbuglink:17779[]

// The Windows installers now ship with Npcap 1.60.
// They previously shipped with Npcap 1.55.

// The Windows installers now ship with USBPcap 1.5.X.0.
// They previously shipped with USBPcap 1.5.4.0.

// The Windows installers now ship with Qt 5.15.2.
// They previously shipped with Qt 5.12.1.

If you’re running Wireshark on macOS and upgraded to macOS 13 from an earlier version, you will likely have to open and run the “Uninstall ChmodBPF” package, then open and run “Install ChmodBPF” in order to reset the ChmodBPF Launch Daemon.
wsbuglink:18734[].

=== Bug Fixes

The following vulnerabilities have been fixed:

* wssalink:2023-09[]
RPCoRDMA dissector crash.
wsbuglink:18852[].
cveidlink:2023-1992[].
// Fixed in master: 3c8be14c82
// Fixed in release-4.0: 04e506a337
// Fixed in release-3.6: c224405c31
// CVSS AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
// CWE-126
// * Fuzz job crash output: fuzz-2023-02-09-6781.pcap. wsbuglink:18852[].

* wssalink:2023-10[]
LISP dissector large loop.
wsbuglink:18900[].
cveidlink:2023-1993[].
// Fixed in master: b911cf286f
// Fixed in release-4.0: 560f328cda
// Fixed in release-3.6: 646b131303
// CVSS AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
// CWE-834
// * Fuzz job crash output: fuzz-2023-03-10-6859.pcap. wsbuglink:18900[].

* wssalink:2023-11[]
GQUIC dissector crash
wsbuglink:18947[].
cveidlink:2023-1994[].
// Fixed in master: ee314ace8a
// Fixed in release-4.0: 9681566329
// Fixed in release-3.6: 8970fc17e8
// CVSS AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
// CWE-476
// * Fuzz job crash output: fuzz-2023-03-31-6903.pcap. wsbuglink:18947[].

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark keeps banging out random chords on your piano and yelling “LIPS LIKE SUGUAR, SUGAR KISSES” because it was funny that one time at a party.

* Wireshark ITS Dissector RTCMEM wrong protocol version selector 2 - should use 1 wsbuglink:18862[].

* Wireshark treats the letter E in SSRC as an exponential representation of a number wsbuglink:18879[].

* VNC RRE Parser skips over data wsbuglink:18883[].

* Fuzz job crash output: fuzz-2023-03-27-7564.pcap wsbuglink:18934[].

* Fuzz job crash output: fuzz-2023-03-31-6903.pcap wsbuglink:18947[].

* RTP analysis shows incorrect timestamp error when timestamp is rolled over wsbuglink:18973[].


=== New and Updated Features

// === Removed Features and Support

// === Removed Dissectors

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
// ag -A1 '(define PSNAME|proto_register_protocol[^_])' $(git diff --name-only v3.6.12.. | ag packet- | sort -u)
[commaize]
--
DNS
ERF
FF
genl
GQUIC
GSM A-bis OML
HL7
IEEE 802.11
ITS
ITS
LISP
netlink
netlink-netfilter
netlink-sock_diag
nl80211
RLC
RPCoRDMA
RTPS
SCTP
SMB
VNC
WCP
--

=== New and Updated Capture File Support

// There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
[commaize]
--
Netmon
NetScaler
--

=== New File Format Decoding Support

There is no new or updated file format support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --


// === New and Updated Capture Interfaces support

//_Non-empty section placeholder._

// === Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages.
You can usually install or upgrade Wireshark using the package management system specific to that platform.
A list of third-party packages can be found on the
https://www.wireshark.org/download.html[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference files, plugins, SNMP MIBS, and RADIUS dictionaries.
These locations vary from platform to platform.
You can use menu:Help[About Wireshark,Folders] or `tshark -G folders` to find the default locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be found at
https://www.wireshark.org/docs/

Community support is available on
https://ask.wireshark.org/[Wireshark’s Q&A site]
and on the wireshark-users mailing list.
Subscription information and archives for all of Wireshark’s mailing lists can be found on
https://www.wireshark.org/lists/[the web site].

Bugs and feature requests can be reported on
https://gitlab.com/wireshark/wireshark/-/issues[the issue tracker].

// Official Wireshark training and certification are available from
// https://www.wiresharktraining.com/[Wireshark University].

== How You Can Help

The Wireshark Foundation helps as many people as possible understand their networks as much as possible.
You can find out more and donate at https://wiresharkfoundation.org[wiresharkfoundation.org].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
