= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2018-05[]
+
The IEEE 802.11 dissector could crash.
(ws-buglink:14442[])
cve-idlink:2018-7335[]
// Fixed in master: 9c5803ff76
// Fixed in master-2.4: 569fb1e21d
// Fixed in master-2.2: 2743040cd4

* ws-salink:2018-06[]
+
Multiple dissectors could go into large infinite loops.
All ASN.1 BER dissectors (ws-buglink:14444[]),
along with the DICOM (ws-buglink:14411[]),
DMP (ws-buglink:14408[]),
LLTD (ws-buglink:14419[]),
OpenFlow (ws-buglink:14420[]),
RELOAD (ws-buglink:14445[]),
RPCoRDMA (ws-buglink:14449[]),
RPKI-Router (ws-buglink:14414[]),
S7COMM (ws-buglink:14423[]),
SCCP (ws-buglink:14413[]),
Thread (ws-buglink:14428[]),
Thrift (ws-buglink:14379[]),
USB (ws-buglink:14421[]),
and WCCP (ws-buglink:14412[])
dissectors were susceptible.
// cve-idlink:2018-xxxx[]
// Fixed in master: lots
// Fixed in master-2.4: lots
// Fixed in master-2.2: lots

* ws-salink:2018-07[]
+
The UMTS MAC dissector could crash.
(ws-buglink:14339[])
cve-idlink:2018-7334[]
// Fixed in master: 9dfd17b104
// Fixed in master-2.4: 8d4398752e
// Fixed in master-2.2: 8ed705e122

* ws-salink:2018-09[]
+
The FCP dissector could crash.
(ws-buglink:14374[])
cve-idlink:2018-7336[]
// Fixed in master: f4f44caa35
// Fixed in master-2.4: af5943168b
// Fixed in master-2.2: b56f598f1b

* ws-salink:2018-10[]
+
The SIGCOMP dissector could crash.
(ws-buglink:14398[])
cve-idlink:2018-7320[]
// Fixed in master: 7da66f8676
// Fixed in master-2.4: 5173221082
// Fixed in master-2.2: 015e339939

* ws-salink:2018-11[]
+
The pcapng file parser could crash.
(ws-buglink:14403[])
// cve-idlink:2018-xxxx[]
// Fixed in master: f73ae69ba9
// Fixed in master-2.4: 52ac26f131
// Fixed in master-2.2: 129e41f9f6

* ws-salink:2018-12[]
+
The IPMI dissector could crash.
(ws-buglink:14409[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 0bd863ae46
// Fixed in master-2.4: 81216a176b
// Fixed in master-2.2: 72ed2229e5,536650a419

* ws-salink:2018-13[]
+
The SIGCOMP dissector could crash.
(ws-buglink:14410[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 32ab83436d
// Fixed in master-2.4: 29d920b830
// Fixed in master-2.2: 0a2f323977

* ws-salink:2018-14[]
+
The NBAP disssector could crash.
(ws-buglink:14443[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 47726eafe5
// Fixed in master-2.4: f87bd6f978
// Fixed in master-2.2: bebd3a1f50

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.2.13rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do ./tools/gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Change placement of "double chevron" in Filter Toolbar to eliminate overlap. (ws-buglink:14121[])

* GET MAX LUN wLength decoded as big-endian - USB Mass Storage. (ws-buglink:14360[])

* Buildbot crash output: fuzz-2018-01-28-15874.pcap. (ws-buglink:14371[])

* [oss-fuzz] #6028 RPC_NETLOGON: Direct-leak in g_malloc (generate_hash_key). (ws-buglink:14407[])


=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
ASN.1 BER
BOOTP/DHCP
DCE RPC NETLOGON
DICOM
DIS
DMP
DOCSIS
IAX2
IEEE 802.11
IPMI
FCP
LLTD
NBAP
OpenFlow
RELOAD
RPCoRDMA
RPKI-Router
S7COMM
SCCP
SIGCOMP
Thread
Thrift
UMTS MAC
USB
USB Mass Storage
WCCP
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
pcapng
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

=== Major API Changes

There are no major API changes in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
