include::attributes.asciidoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

This is expected to be the final release of the Wireshark 3.0 branch.
It will reach its official end of life https://gitlab.com/wireshark/editor-wiki/-/wikis/Development/LifeCycle#end-of-life-planning[when Wireshark 3.4.0 is released].
If you are still using Wireshark 3.0 you are encouraged to upgrade to Wireshark 3.2 or 3.4.

The Windows installers now ship with Qt 5.12.9.
They previously shipped with Qt 5.12.8.

=== Bug Fixes

// The following vulnerabilities have been fixed:

// * wssalink:2020-11[]
// Foo dissector {crash,infinite loop}.
// wsbuglink:xxxx[].
// cveidlink:2020-xxxx[].
// Fixed in master: xxxx
// Fixed in master-3.2: xxxx
// Fixed in master-3.0: xxxx
// Fixed in master-2.6: xxxx

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark slowly leaked water under the kitchen sink over the course of several months, causing a big mess.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v3.0.14rc0.. | gsed -e 's/\(close\|fix\|resolv\)[^ ]* #/\nclose #/gI' | grep ^close | sed -e 's/close.*#\([1-9][0-9]*\).*/\1/' | sort -V -u` ; do "$(git rev-parse --show-toplevel)/tools/gen-bugnote" $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Buildbot crash output: randpkt-2019-04-01-28345.pcap wsbuglink:15661[].

* Buildbot crash output: fuzz-2020-07-28-5905.pcap wsbuglink:16741[].

* ERROR:epan/proto.c:9868:hfinfo_number_value_format_display: code should not be reached wsbuglink:16816[].

* S1-U data forwarding info and S103 PDN data forwarding info IE's showing improper value wsbuglink:16777[].

* The client timestamp is parsed error for Google QUIC (version Q039) wsbuglink:16839[].

* Wireshark fails to detect libssh >= 0.9.5 wsbuglink:16845[].


=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

// === New File Format Decoding Support

// [commaize]
// --
// --

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
AARP
BSSMAP
GQUIC
GSM A RR
GTPv2
MIME Multipart
NCP
NDS
PFCP
PROFINET
Q.933
TACACS+
TCP
S1AP
X2AP
--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --

=== New and Updated Capture Interfaces support

There is no new or updated capture file support in this release.
// [commaize]
// --
// --

// === Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be
found at https://www.wireshark.org/docs/

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Bugs and feature requests can be reported on
https://bugs.wireshark.org/[the bug tracker].

// Official Wireshark training and certification are available from
// http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
