= Wireshark wireshark-version:[] Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

This is a semi-experimental release intended to test new features for Wireshark 2.2.

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

//=== Bug Fixes

//The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])

The following vulnerabilities have been fixed.

* ws-salink:2015-31[]
+
NBAP dissector crashes.
// Fixed in master: g5bf5656, g5b4ada1, g23379ae
// Fixed in master-2.0: gfa117e7, g254731e
// Fixed in master-1.12: gdaa562c, g3e1cd49, g884d49c
(ws-buglink:11602[], ws-buglink:11835[], ws-buglink:11841[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-37[]
+
NLM dissector crash.
// Fixed in master: g81dfe6d
// Fixed in master-2.0: g851782c
// Fixed in master-1.12: g916dfc5
//(ws-buglink:[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-39[]
+
BER dissector crash.
// Fixed in master: g921bb07
// Fixed in master-2.0: g1e52fad
// Fixed in master-1.12: g2c59970
// (ws-buglink:[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-40[]
+
Zlib decompression crash.
// Fixed in master: gcec0593
// Fixed in master-2.0: g7ea63cf
// Fixed in master-1.12: gff0220f
(ws-buglink:11548[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-41[]
+
SCTP dissector crash.
// Fixed in master: g2259bf8, g1b32d50
// Fixed in master-2.0: ga77290c, ga9b4be9
// Fixed in master-1.12: g39a50f4
(ws-buglink:11767[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-42[]
+
802.11 decryption crash.
// Fixed in master: g40b2831, 83f2818
// Fixed in master-2.0: gbf1fa88, gfc3b6a5
// Fixed in master-1.12: ga6e8fc8, g8110a70
(ws-buglink:11790[], ws-buglink:11826[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-43[]
+
DIAMETER dissector crash.
// Fixed in master: gaaa28a9
// Fixed in master-2.0: g92c892e
// Fixed in master-1.12: g644bc78
(ws-buglink:11792[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-44[]
+
VeriWave file parser crashes.
// Fixed in master: gb8fa3d4, 185911d
// Fixed in master-2.0: g135c8f0, ge4267dd
// Fixed in master-1.12: gfef89fc, g51ccf92
(ws-buglink:11789[], ws-buglink:11791[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-45[]
+
RSVP dissector crash.
// Fixed in master: g56baca6
// Fixed in master-2.0: g9764685
// Fixed in master-1.12: g5d20997
(ws-buglink:11793[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-46[]
+
ANSI A & GSM A dissector crashes.
// Fixed in master: g15edc8d
// Fixed in master-2.0: g61dcd11
// Fixed in master-1.12: g8194323
(ws-buglink:11797[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-47[]
+
Ascend file parser crash.
// Fixed in master: g338da1c
// Fixed in master-2.0: g7abfa36
// Fixed in master-1.12: g9cf09cf
(ws-buglink:11794[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-48[]
+
NBAP dissector crash.
// Fixed in master: gd2644ae
// Fixed in master-2.0: g4c499f5
// Fixed in master-1.12: gea517f9
(ws-buglink:11815[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-49[]
+
RSL dissector crash.
// Fixed in master: g2930d31
// Fixed in master-2.0: gaba3635
// Fixed in master-1.12: gf899e8a
(ws-buglink:11829[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-50[]
+
ZigBee ZCL dissector crash.
// Fixed in master: g9352616, geb0c034
// Fixed in master-2.0: gb11c868, g07dbf78
// Fixed in master-1.12: g49e7e7f, g6b3755c
(ws-buglink:11830[])
//cve-idlink:2015-XXXX[]

* ws-salink:2015-51[]
+
Sniffer file parser crash.
// Fixed in master: g53a3e53
// Fixed in master-2.0: gdcba250
// Fixed in master-1.12: g3a3ddbd
(ws-buglink:11827[])
//cve-idlink:2015-XXXX[]

=== New and Updated Features

The following features are new (or have been significantly updated)
since version 2.0.0:
** You can now switch between between Capture and File Format dissection of
the current capture file via the View menu in the Qt GUI.

//=== Removed Dissectors

=== New File Format Decoding Support

Wireshark is able to display the format of some types of files (rather than
displaying the contents of those files). This is useful when you're curious
about, or debugging, a file and its format.  To open a capture file (such as
PCAP) in this mode specify "MIME Files Format" as the file's format in the
Open File dialog.

New files that Wireshark can open in this mode include:

_Non-empty section placeholder._
--sort-and-group--
--sort-and-group--

=== New Protocol Support
CISCO ERSPAN3 Marker
Nokia Intelligent Service Interface (ISI)
ISO14443
Extensible Control & Management Protocol (eCMP)
RTI TCP Transport Layer (RTITCP)
// Items in --sort-and-group-- blocks will be sorted and comma-separated.
--sort-and-group--
--sort-and-group--

=== Updated Protocol Support

Too many protocols have been updated to list here.

=== New and Updated Capture File Support

_Non-empty section placeholder._
--sort-and-group--
--sort-and-group--

=== New and Updated Capture Interfaces support

_Non-empty section placeholder._
--sort-and-group--
--sort-and-group--

=== Major API Changes

The libwireshark API has undergone some major changes:

* The address macros (e.g., SET_ADDRESS) have been removed.  Use the
(lower case) functions of the same names instead.

* "old style" dissector functions (that don't return number of bytes
used) have been replaced in name with the "new style" dissector
functions.

* tvb_get_string and tvb_get_stringz have been replaced with
tvb_get_string_enc and tvb_get_stringz_enc respectively.


== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

The 64-bit version of Wireshark will leak memory on Windows when the display
depth is set to 16 bits (ws-buglink:9914[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
