= Wireshark wireshark-version:[] Release Notes

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

// Link templates: ws-buglink:5000[]  ws-buglink:6000[Wireshark bug]  cve-idlink:2016-7000[]

The following vulnerabilities have been fixed:

* ws-salink:2016-29[]
+
The SPOOLS dissector could go into an infinite loop.
Discovered by the CESG.
//(ws-buglink:xxxxx[])
//cve-idlink:2015-XXXX[]
// Fixed in master: b4d16b4
// Fixed in master-2.0: 9753ea8
// Fixed in master-1.12: 9310b88

* ws-salink:2016-30[]
+
The IEEE 802.11 dissector could crash.
(ws-buglink:11585[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 9b0b20b
// Fixed in master-2.0: 3456d09
// Fixed in master-1.12: f2c0a28, 2297b62

* ws-salink:2016-32[]
+
The UMTS FP dissector could crash.
(ws-buglink:12191[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 7d71906
// Fixed in master-2.0: ff27d85
// Fixed in master-1.12: fb9dcfa

* ws-salink:2016-33[]
+
Some USB dissectors could crash. Discovered by Mateusz Jurczyk.
(ws-buglink:12356[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 2cb5985
// Fixed in master-2.0: 20e7875
// Fixed in master-1.12: 7f77886

* ws-salink:2016-34[]
+
The Toshiba file parser could crash. Discovered by iDefense Labs.
(ws-buglink:12394[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 3270dfa
// Fixed in master-2.0: f5e7e03
// Fixed in master-1.12: edbed5a

* ws-salink:2016-35[]
+
The CoSine file parser could crash. Discovered by iDefense Labs.
(ws-buglink:12395[])
//cve-idlink:2015-XXXX[]
// Fixed in master: a66628e
// Fixed in master-2.0: 45fc804
// Fixed in master-1.12: 1635420

* ws-salink:2016-36[]
+
The NetScreen file parser could crash. Discovered by iDefense Labs.
(ws-buglink:12396[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 11edc83
// Fixed in master-2.0: 2916518
// Fixed in master-1.12: 4f4e1cb

* ws-salink:2016-37[]
+
The WBXML dissector could go into an infinite loop.
Discovered by Chris Benedict, Aurelien Delaitre, NIST SAMATE Project.
(ws-buglink:12408[])
//cve-idlink:2015-XXXX[]
// Fixed in master: n/a
// Fixed in master-2.0: n/a
// Fixed in master-1.12: b8e0d41

The following bugs have been fixed:

//* Wireshark always manages to score tickets for Burning Man, Coachella, and
//  SXSW while you end up working double shifts. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v1.12.12rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Saving pcap capture file with ERF encapsulation creates an invalid pcap file. (ws-buglink:3606[])

* Don't copy details of hidden columns. (ws-buglink:11788[])

* The stream number in tshark's "-z follow,tcp,<stream number>" option is 0-origin rather than 1-origin. (ws-buglink:12383[])

* ICMPv6 dissector doesn't respect actual packet length. (ws-buglink:12400[])

* Format DIS header timestamp mm:ss.nnnnnn. (ws-buglink:12402[])

* Ethernet type field with a value of 9100 is shown as "Unknown". (ws-buglink:12441[])

* SMB Open andX extended response decoded incorrectly. (ws-buglink:12472[])

Windows installers and PortableApps(R) packages are dual signed using SHA-1 and SHA-256
in order to comply with
http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx[Microsoft Authenticode policy].
Windows 7 and Windows Server 2008 R2 users should ensure that
https://support.microsoft.com/en-us/kb/3123479[update 3123479] is installed.
Windows Vista and Windows Server 2008 users should ensure that
https://support.microsoft.com/en-us/kb/2763674[hotfix 2763674] is installed.

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
CSN.1
DIS
Ethernet
GSM A RR
LTE-RRC
ICMPv6
IEEE 802.11
JXTA
LAPSat
LPADm
OpenFlow
P1
SMB
SPOOLSS
USB
UMTS FP
WBXML
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
Aethra
CoSine
DBS Etherwatch
ERF
iSeries
Ixia IxVeriWave
NetScreen
Toshiba
VMS TCPIPtrace
--sort-and-group--

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
