= Wireshark wireshark-version:[] Release Notes
// $Id$

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed.

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* ws-salink:2013-11[]
//* cve-idlink:2013-2486[]

* ws-salink:2013-54[]
+
The Bluetooth HCI ACL dissector could crash. Discovered by Laurent Butti.
// Fixed in trunk: r50268
// Fixed in trunk-1.10: r51330
(ws-buglink:????[])
+
Versions affected: 1.10.0 to 1.10.2
//+
//cve-idlink:2013-????[]

* ws-salink:2013-55[]
+
The NBAP dissector could crash. Discovered by Laurent Butti.
// Fixed in trunk: r51195
// Fixed in trunk-1.10: r51228
// Fixed in trunk-1.8: r51230
(ws-buglink:????[])
+
Versions affected: 1.10.0 to 1.10.1, 1.8.0 to 1.8.9
//+
//cve-idlink:2013-????[]

* ws-salink:2013-56[]
+
The ASSA R3 dissector could crash. Discovered by Ben Schmidt.
// Fixed in trunk: r51196
// Fixed in trunk-1.10: r51231
// Fixed in trunk-1.8: r51232
(ws-buglink:????[])
+
Versions affected: 1.10.0 to 1.10.1, 1.8.0 to 1.8.9
//+
//cve-idlink:2013-????[]

* ws-salink:2013-57[]
+
The RTPS dissector could crash. Discovered by Ben Schmidt.
// Fixed in trunk: r51213
// Fixed in trunk-1.10: r51623
// Fixed in trunk-1.8: r51624
(ws-buglink:????[])
+
Versions affected: 1.10.0 to 1.10.1, 1.8.0 to 1.8.9
//+
//cve-idlink:2013-????[]

* ws-salink:2013-58[]
+
The ? dissector could crash. Discovered by ?.
// Fixed in trunk: r?
// Fixed in trunk-1.10: r?
// Fixed in trunk-1.8: r?
(ws-buglink:????[])
+
Versions affected: 1.10.0 to 1.10.1, 1.8.0 to 1.8.9
//+
//cve-idlink:2013-????[]


* ws-salink:2013-59[]
+
The MQ dissector could crash.
// Fixed in trunk: r51603
// Fixed in trunk-1.10: r51623
// Fixed in trunk-1.8: r51624
(ws-buglink:????[])
+
Versions affected: 1.10.0 to 1.10.1, 1.8.0 to 1.8.9
//+
//cve-idlink:2013-????[]

* ws-salink:2013-60[]
+
The LDAP dissector could crash.
// Fixed in trunk: r51516
// Fixed in trunk-1.10: r51623
// Fixed in trunk-1.8: r51624
(ws-buglink:????[])
+
Versions affected: 1.10.0 to 1.10.1, 1.8.0 to 1.8.9
//+
//cve-idlink:2013-????[]


The following bugs have been fixed:

//* Wireshark will practice the jazz flute for hours on end when you're trying to sleep. ws-buglink:0000[]

* "Edit Interface Settings": "Capture Filter" combo box is not populated across Wireshark sessions. (ws-buglink:7278[])

* PER normally small non-negative whole number decoding is wrong when >= 64. (ws-buglink:8841[])

* Strange behavior of tree expand/collapse in packet details. (ws-buglink:8908[])

* Incorrect parsing of IPFIX *IpTotalLength elements. (ws-buglink:8918[])

* IO graph/advanced, max/min/summ error on frames with multiple Diameter messages. (ws-buglink:8980[])

* pod2man error on reordercap.pod. (ws-buglink:8982[])

* SGI Nsym disambiguation is unconditionally displayed when dissecting VHT. (ws-buglink:8989[])

* The Wireshark icon doesn't show up in OS X 10.5. (ws-buglink:8993[])

* Build fails if system Python is version 3+. (ws-buglink:8995[])

* SCSI dissector does not parse PERSISTENT RESERVE commands correctly. (ws-buglink:9012[])

* SDP messages throws an assert. (ws-buglink:9022[])

* Wireshark fails to decode single-line, multiple Contact: URIs in SIP responses. (ws-buglink:9031[])

* PN_MRP LinkUp Message is shown as LinkDown in info. (ws-buglink:9035[])

* Dissector for EtherCAT: ADS highlighting in the Packet Bytes Pane is incorrect. (ws-buglink:9036[])

* 802.11 HT Extended Capabilities B10 decode incorrect. (ws-buglink:9038[])

* Wrong dissection of MSTI Root Identifiers for all MSTIs. (ws-buglink:9088[])

* Warning for attempting to install 64-bit Wireshark on a 32-bit machine has an embedded "\n". (ws-buglink:9103[])

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--

ASN.1 PER
ASSA R3
Bluetooth HCI ACL
EtherCAT AMS
IEEE 802.11
IPFIX
LDAP
MQ
NBAP
Novell SSS
PROFINET MRP
Radiotap
ROHC
RTPS
SCSI
SIP
STP

--sort-and-group--

=== New and Updated Capture File Support

--sort-and-group--

Microsoft Network Monitor, pcap-ng.

--sort-and-group--

== Getting Wireshark

Wireshark source code and installation packages are available from
http://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the http://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Summary pane selected frame highlighting not maintained.
(ws-buglink:4445[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

== Getting Help

Community support is available on http://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on http://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
http://www.wireshark.org/faq.html[Wireshark web site].
