= Wireshark wireshark-version:[] Release Notes

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following bugs have been fixed:

// Link templates: ws-buglink:5000[]  ws-buglink:6000[Wireshark bug]  cve-idlink:2013-2486[]

The following vulnerabilities have been fixed.

* ws-salink:2014-13[]
+
MEGACO dissector infinite loop.
// Fixed in master: g9112a09
// Fixed in master-1.12: g6295e53
// Fixed in master-1.10: gfeed72f
(ws-buglink:10333[])
cve-idlink:2014-6423[]

* ws-salink:2014-14[]
+
Netflow dissector crash.
// Fixed in master: g4469825
// Fixed in master-1.12: g2035d31
// Fixed in master-1.10: g6e67016
(ws-buglink:10370[])
cve-idlink:2014-6424[]

* ws-salink:2014-15[]
+
CUPS dissector crash.
// Fixed in master: gc10396d
// Fixed in master-1.12: g2035d31
(ws-buglink:10353[])
cve-idlink:2014-6425[]

* ws-salink:2014-16[]
+
HIP dissector infinite loop.
// Fixed in master: gd9e5021
// Fixed in master-1.12: g9069d7b
cve-idlink:2014-6426[]

* ws-salink:2014-17[]
+
RTSP dissector crash.
// Fixed in master: g7395915
// Fixed in master-1.12: g949cca0
// Fixed in master-1.10: gd762bd3
(ws-buglink:10381[])
cve-idlink:2014-6427[]

* ws-salink:2014-18[]
+
SES dissector crash.
// Fixed in master: g433a444
// Fixed in master-1.12: g0942b2c
// Fixed in master-1.10: g6763e8d
(ws-buglink:10454[])
cve-idlink:2014-6428[]

* ws-salink:2014-19[]
+
Sniffer file parser crash.
// Fixed in master: g47c5929
// Fixed in master-1.12: g4413725
// Fixed in master-1.10: g9a7abcc
(ws-buglink:10461[])
cve-idlink:2014-6429[]
cve-idlink:2014-6430[]
cve-idlink:2014-6431[]
cve-idlink:2014-6432[]


The following bugs have been fixed:

//* Wireshark always manages to score tickets for Burning Man, Coachella, and
//  SXSW while you end up working double shifts. (ws-buglink:0000[])

* Wireshark can crash during remote capture (rpcap) configuration.
  (ws-buglink:3554[], ws-buglink:6922[], ws-buglink:7021)

* 802.11 capture does not decrypt/decode DHCP response. (ws-buglink:8734[])

* Extra quotes around date fields (FT_ABSOLUTE_TIME) when using -E quote=d or s. (ws-buglink:10213[])

* No progress line in "VOIP RTP Player". (ws-buglink:10307[])

* MIPv6 Service Selection Identifier parse error. (ws-buglink:10323[])

* Probably wrong length check in proto_item_set_end. (ws-buglink:10329[])

* 802.11 BA sequence number decode is broken. (ws-buglink:10334[])

* wmem_alloc_array() "succeeds" (and clobbers memory) when requested to allocate
  0xaaaaaaaa items of size 12. (ws-buglink:10343[])

* Different dissection results for same file. (ws-buglink:10348[])

* Mergecap wildcard breaks in version 1.12.0. (ws-buglink:10354[])

* Diameter TCP reassemble. (ws-buglink:10362[])

* TRILL NLPID 0xc0 unknown to Wireshark. (ws-buglink:10382[])

* BTLE advertising header flags (RxAdd/TxAdd) dissected incorrectly.
  (ws-buglink:10384[])

* Ethernet OAM (CFM) frames including TLV's are wrongly decoded as malformed.
  (ws-buglink:10385[])

* BGP4: Wireshark skipped some potion of AS_PATH. (ws-buglink:10399[])

* MAC address name resolution is broken. (ws-buglink:10344[])

* Wrong decoding of RPKI RTR End of Data PDU. (ws-buglink:10411[])

* SSL/TLS dissector incorrectly interprets length for status_request_v2 hello
  extension. (ws-buglink:10416[])

* Misparsed NTP control assignments with empty values. (ws-buglink:10417[])

* 6LoWPAN multicast address decompression problems. (ws-buglink:10426[])

* Netflow v9 flowset not decoded if options template has zero-length scope
  section. (ws-buglink:10432[])

* GUI Hangs when Selecting Path to GeoIP Files. (ws-buglink:10434[])

* AX.25 dissector prints unprintable characters. (ws-buglink:10439[])

* 6LoWPAN context handling not working. (ws-buglink:10443[])

* SIP: When export to a CSV, Info is changed to differ. (ws-buglink:10453[])

* Typo in packet-netflow.c. (ws-buglink:10458[])

* Incorrect MPEG-TS decoding (OPCR field). (ws-buglink:10446[])

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
6LoWPAN
A21
ACR122
Art-Net
AX.25
BGP
BTLE
CAPWAP
Ethernet OAM
DIAMETER
DICOM
DVB-CI
HIP
HiSLIP
HTTP2
IEEE 802.11
MAUSB
MEGACO
MIPv6
MP2T
Netflow
NTP
openSAFETY
OSI
RDM
RPKI RTR
RTSP
SES
SIP
TLS
Token Ring MAC
--sort-and-group--

=== New and Updated Capture File Support

--sort-and-group--
DOS Sniffer
NetScaler
--sort-and-group--

== Getting Wireshark

Wireshark source code and installation packages are available from
http://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the http://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814)

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Summary pane selected frame highlighting not maintained.
(ws-buglink:4445[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

The 64-bit Mac OS X installer doesn't support Mac OS X 10.9 (ws-buglink:9242[])

== Getting Help

Community support is available on http://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on http://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
http://www.wireshark.org/faq.html[Wireshark web site].
