= Wireshark wireshark-version:[] Release Notes

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed.

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* ws-salink:2013-11[]
//* cve-idlink:2013-2486[]

* ws-salink:2014-08[]
+
The Catapult DCT2000 and IrDA dissectors could underrun a buffer.
// Fixed in master: g16f8ba1
// Fixed in master-1.12: g71cb629 (prior to 1.12.0)
// Fixed in master-1.10: gcdb8710
//(ws-buglink:9999[], ws-buglink:10030[])
+
Versions affected: 1.10.0 to 1.10.8
//+
//cve-idlink:2014-0000[]

* ws-salink:2014-09[]
+
The GSM Management dissector could crash.
// Fixed in master: gdd7134d, g3fc441e
// Fixed in master-1.12: gc7874f7, ga3e3db5 (prior to 1.12.0)
// Fixed in master-1.10: gabae269, g975297b
(ws-buglink:10216[])
+
Versions affected: 1.10.0 to 1.10.8
//+
//cve-idlink:2014-0000[]

* ws-salink:2014-10[]
+
The RLC dissector could crash.
// Fixed in master: gba6eb5c
// Fixed in master-1.12: g2c877e0 (prior to 1.12.0)
// Fixed in master-1.10: gf608926
(ws-buglink:9795[])
+
Versions affected: 1.10.0 to 1.10.8
//+
//cve-idlink:2014-0000[]

* ws-salink:2014-11[]
+
The ASN.1 BER dissector could crash.
// Fixed in master: g17a5526
// Fixed in master-1.12: gd0156c4 (prior to 1.12.0)
// Fixed in master-1.10: g1eb9b9e
(ws-buglink:10187[])
+
Versions affected: 1.10.0 to 1.10.8
//+
//cve-idlink:2014-0000[]

The following bugs have been fixed:

// Should be sorted numerically.
// * Wireshark will practice the jazz flute for hours on end when you're trying to sleep. (ws-buglink:0000[])
* GSM MAP: ensure that p2p_dir is always initialized before calling GSM SMS dissector (ws-buglink:10234[])
* BFCP: include padding length in calculation of correct attribute length (ws-buglink:10240[])
* GTP: allow empty Data Record Packet IE (ws-buglink:10277[])
* WebSocket: increase max unmask payload size to 256K and indicate that packet is truncated is going above the new limit (ws-buglink:10283[])

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--

--sort-and-group--

=== New and Updated Capture File Support

--sort-and-group--

--sort-and-group--

== Getting Wireshark

Wireshark source code and installation packages are available from
http://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the http://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Summary pane selected frame highlighting not maintained.
(ws-buglink:4445[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

== Getting Help

Community support is available on http://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on http://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
http://www.wireshark.org/faq.html[Wireshark web site].
