include::attributes.asciidoc[]

= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* wssalink:2018-47[]
+
MS-WSP dissector crash.
wsbuglink:15119[].
cveidlink:2018-18227[].
// Fixed in master: f4d2dffd8b
// Fixed in master-2.6: 536fb9403a
// Fixed in master-2.4: e2bc6abff0

* wssalink:2018-50[]
+
OpcUA dissector crash.
//wsbuglink:15172[].
cveidlink:2018-12086[].
// Fixed in master: 28a7a79cac
// Fixed in master-2.6: fc956747a1
// Fixed in master-2.4: d8df84879b

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark keeps leaving voicemails advertising timeshare condominiums in Fresno. (wsbuglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.4.11rc0..| grep ' Bug:' | awk '{print $2}' | sort -n -u ` ; do ./tools/gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* HTTP2 dissector decodes first SSL record only. wsbuglink:11173[].

* Undocumented sub-option for -N option in man page and tshark -N help. wsbuglink:14826[].

* Mishandling of Port Control Protocol option padding. wsbuglink:14950[].

* MGCP: parameter lines are case-insensitive. wsbuglink:15008[].

* details of 2nd sub-VSA in bundled RADIUS VSA are incorrect. wsbuglink:15073[].

* Heuristic DPLAY dissector fails to recognize DPLAY packets. wsbuglink:15092[].

* gsm_rlcmac_dl dissector exception. wsbuglink:15112[].

* Buildbot crash output: fuzz-2018-09-07-29306.pcap. wsbuglink:15119[].

* Wildcard expansion doesn't work on Windows 10 for command-line programs in cmd.exe or PowerShell. wsbuglink:15151[].

* SSL Reassembly Error New fragment past old data limits. wsbuglink:15158[].

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
ASN.1 PER
DPLAY
CIP
HTTP
MGCP
MS-WSP
OpcUa
PCP
RADIUS
TLS
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
Ascend
pcapng
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.
//--sort-and-group--
//--sort-and-group--

//=== Major API Changes

//_Non-empty section placeholder._

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(wsbuglink:1419[])

The BER dissector might infinitely loop.
(wsbuglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(wsbuglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(wsbuglink:2234[])

Application crash when changing real-time option.
(wsbuglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(wsbuglink:4985[])

Wireshark should let you work with multiple capture files. (wsbuglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
