= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2018-25[]
+
The LDSS dissector could crash.
(ws-buglink:14615[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 295abe2e83
// Fixed in master-2.6: 35344225fa
// Fixed in master-2.4: 6fe7632af0
// Fixed in master-2.2: f177008b04

* ws-salink:2018-28[]
+
Multiple dissectors could consume excessive memory.
(ws-buglink:14678[])
// cve-idlink:2018-xxxx[]
// Fixed in master: d80acae40d
// Fixed in master-2.6: b82a9a3f95
// Fixed in master-2.4: ac55e80ae4
// Fixed in master-2.2: ab8a33ef08

* ws-salink:2018-29[]
+
The DNS dissector could crash.
(ws-buglink:14681[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 843735e0ef
// Fixed in master-2.6: d93f7b8707
// Fixed in master-2.4: 95c884e78f
// Fixed in master-2.2: 4425716ddb

* ws-salink:2018-30[]
+
The GSM A DTAP dissector could crash.
(ws-buglink:14688[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 48fac2a18d
// Fixed in master-2.6: 521dcb0b84
// Fixed in master-2.4: c79b342aa7
// Fixed in master-2.2: a55b36c51f

* ws-salink:2018-31[]
+
The Q.931 dissector could crash.
(ws-buglink:14689[])
// cve-idlink:2018-xxxx[]
// Fixed in master: d08a53a7b9
// Fixed in master-2.6: e1deea1169
// Fixed in master-2.4: 0e67d8b5ee
// Fixed in master-2.2: ccb1ac3c8c

* ws-salink:2018-33[]
+
Multiple dissectors could crash.
(ws-buglink:14703[])
// cve-idlink:2018-xxxx[]
// Fixed in master: 40dbc0ccf2
// Fixed in master-2.6: e50f7ced83
// Fixed in master-2.4: fb9e31f0aa
// Fixed in master-2.2: beaebe91b1

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.2.15rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do ./tools/gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* SMB2 Write requests not displayed. (ws-buglink:14598[])

* Wrong default file format chosen in when saving a capture with comments added if the original format doesn't support comments. (ws-buglink:14601[])

* WinSparkle 0.5.6 is out of date and is buggy. (ws-buglink:14642[])


=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
BATADV
BSSMAP
BVLC
DNS
GSM A DTAP
GTP
IEEE 802.11
LDSS
Logcat Text
MP2T
MPEG PES
NBSS
Q.931
S7COMM
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
Android Logcat
3GPP TS 32.423 Trace
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

=== Major API Changes

There are no major API changes in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
