= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2017-38[]
+
MSDP dissector infinite loop
(ws-buglink:13933[])
// cve-idlink:2017-xxxx[]
// Fixed in master: 33b95883aa
// Fixed in master-2.4: a6d312cce1
// Fixed in master-2.2: 5ade15dbd6
// Fixed in master-2.0: 6f18ace2a2

* ws-salink:2017-39[]
+
Profinet I/O buffer overrun
(ws-buglink:13847[])
// cve-idlink:2017-xxxx[]
// Fixed in master: 5574b78dae
// Fixed in master-2.4: 1c95d45a40
// Fixed in master-2.2: 2096bc1e50
// Fixed in master-2.0: n/a

* ws-salink:2017-41[]
+
IrCOMM dissector buffer overrun
(ws-buglink:13929[])
// cve-idlink:2017-xxxx[]
// Fixed in master: c9cb01adbb
// Fixed in master-2.4: a8668a1561
// Fixed in master-2.2: cbf91bab71
// Fixed in master-2.0: 94666d4357

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.2.10rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Confusing "Apply a display filter <Command/>" keyboard shortcut. (ws-buglink:12450[])

* VNC Protocol disector : Framebuffer Updates. (ws-buglink:13910[])

* DNS LOC RRs with out-of-range longitude or latitude aren't shown as errors. (ws-buglink:13914[])

* DIS Dissector Entity Appearance Record displayed in wrong location. (ws-buglink:13917[])

* Win64 CMake bug - (CYGWIN_INSTALL_PATH redefinition) causing missing packages when using CMake 3.9.0. (ws-buglink:13922[])

* APL records parsed incorrectly for IPv4 prefixes. (ws-buglink:13923[])

* TCAP SRT Analysis incorrectly matched TCAP begins and ends. (ws-buglink:13926[])

* E.212: Check length before trying 3-digits MNC. (ws-buglink:13935[])

* Crash in Wireshark using Dumper:dump() from Lua. (ws-buglink:13944[])

* GTPv2 - decoding issue for Packet Flow ID (type 123). (ws-buglink:13987[])

* [oss-fuzz] BGP memleak: ASAN: 276 byte(s) leaked in 5 allocation(s). (ws-buglink:13995[])

* 802.11 wlan.ft.subelem.r0kh_id should be sequence of bytes. (ws-buglink:14004[])


=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
APL
BGP
DIS
DNS
E.212
GTPv2
IEEE 802.11
InfiniBand
MSDP
MTP2
Profinet I/O
SML
TCAP
VNC
--sort-and-group--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
//--sort-and-group--
//--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

=== Major API Changes

There are no major API changes in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
