= Wireshark wireshark-version:[] Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

* Invalid coloring rules are now disabled instead of discarded. This will
  provide forward compatibility with a coloring rule change in Wireshark 2.2.

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2016-50[]
+
QNX6 QNET dissector crash.
(ws-buglink:11850[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 1396f6a
// Fixed in master-2.2: 291e6d2
// Fixed in master-2.0: 4451dc8

* ws-salink:2016-51[]
+
H.225 dissector crash.
(ws-buglink:12700[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 6d82619
// Fixed in master-2.2: 8eb7e54
// Fixed in master-2.0: f5c7b56

* ws-salink:2016-52[]
+
Catapult DCT2000 dissector crash.
(ws-buglink:12750[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 2e37b27
// Fixed in master-2.2: 70a6b83
// Fixed in master-2.0: 2024fd0

* ws-salink:2016-53[]
+
UMTS FP dissector crash.
(ws-buglink:12751[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 315bba7
// Fixed in master-2.2: 7dc8d30
// Fixed in master-2.0: 1531d53

* ws-salink:2016-54[]
+
Catapult DCT2000 dissector crash.
(ws-buglink:12752[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 3b97fbd
// Fixed in master-2.2: 70a6b83
// Fixed in master-2.0: 2024fd0

* ws-salink:2016-55[]
+
IPMI trace dissector crash.
(ws-buglink:12782[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 5213496
// Fixed in master-2.2: f9598b8
// Fixed in master-2.0: 26daf4a

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2016-7000[]
//* Wireshark insists on calling you on your land line which is keeping you from abandoning it for cellular. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.0.7rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Apply display filter when changing configuration profiles. (ws-buglink:6130[])

* Unrecognized text: CDATA in XML not parsed correctly. (ws-buglink:11755[])

* asn2wrs.py "Unexpected token" error. (ws-buglink:12621[])

* PMKID is incorrectly decoded under RSN Vendor specific IE in EAPOL packet 1. (ws-buglink:12675[])

* CIP dissector fails tvb initialization assertion. (ws-buglink:12676[])

* GTP: Decoding of NSAPI is broken in version 2.0.5. (ws-buglink:12686[])

* Small bug in Modbus (mbtcp.c/h) dissector exception information. (ws-buglink:12693[])

* Upgrading to latest version uninstalls Microsoft Visual C++ redistributable. (ws-buglink:12712[])

* ZGP encrypted differencce between packet details and bytes. (ws-buglink:12728[])

* Crash in ISAKMP dissector after modifying UAT with IKEv2 keys. (ws-buglink:12748[])

* Incorrect parsing of NLMv4 FREE_ALL request. (ws-buglink:12764[])

* Malformed Packet: CDP (forced entry aging). (ws-buglink:12767[])

* tshark -z io,stat does not count frame not correctly when applying an interval of 0. (ws-buglink:12778[])

* MODE SENSE 10 : Mode parameter header 10 : block descriptor length needs to be 2 bytes not 1 byte. (ws-buglink:12780[])

* Organization Specific Slow Protocol dissection errors when retrieving OUI. (ws-buglink:12801[])

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Resolving (ws-buglink:9044[]) reopens (ws-buglink:3528[]) so that Wireshark
no longer automatically decodes gzip data when following a TCP stream.

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

The 64-bit version of Wireshark will leak memory on Windows when the display
depth is set to 16 bits (ws-buglink:9914[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
