= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2017-42[]
+
BT ATT dissector crash
(ws-buglink:14049[])
// cve-idlink:2017-xxxx[]
// Fixed in master: 3689dc1db3
// Fixed in master-2.4: bc6f4f898f
// Fixed in master-2.2: c1d26587c5
// Fixed in master-2.0: n/a

* ws-salink:2017-43[]
+
MBIM dissector crash
(ws-buglink:14056[])
// cve-idlink:2017-xxxx[]
// Fixed in master: afb9ff7982
// Fixed in master-2.4: 9b91a80d4a
// Fixed in master-2.2: b2f5c773fb
// Fixed in master-2.0: n/a

* ws-salink:2017-44[]
+
DMP dissector crash
(ws-buglink:14068[])
// cve-idlink:2017-xxxx[]
// Fixed in master: 8dbb21dfde
// Fixed in master-2.4: 3d8f82c24f
// Fixed in master-2.2: cd2a1e9a8d
// Fixed in master-2.0: bf1f1fd864

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.2.10rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

// Left off at 1539d6f188

* Wireshark crash when end capturing with "Update list of packets in real-time" option off. (ws-buglink:13024[])

* Diameter service response time statistics broken in 2.2.4. (ws-buglink:13442[])

* Some Infiniband Connect Req fields are not decoded correctly. (ws-buglink:13997[])

* wireshark-2.4.1/epan/dissectors/packet-dmp.c:1034: sanity check in wrong place ?. (ws-buglink:14016[])

* [oss-fuzz] ASAN: 232 byte(s) leaked in 4 allocation(s). (ws-buglink:14025[])

* [oss-fuzz] ASAN: 47 byte(s) leaked in 1 allocation(s). (ws-buglink:14032[])

* RTP Analysis "save as CSV" saves twice the forward stream, if two streams are selected. (ws-buglink:14040[])

* Cannot Apply Bitmask to Long Unsigned. (ws-buglink:14063[])

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
BT ATT
DCERPC
DMP
E.212
H.248
InfiniBand
MBIM
RPC
WSP
--sort-and-group--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
//--sort-and-group--
//--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

=== Major API Changes

There are no major API changes in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
