include::attributes.adoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

This is an experimental release intended to test new features for Wireshark 3.4.

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

Many improvements have been made.
See the “New and Updated Features” section below for more details.

// === Bug Fixes

// The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark exposed details your sordid redneck past, which were subsequently widely dissemenated on social media.

=== New and Updated Features

The following features are new (or have been significantly updated)
since version 3.2.0:

* Windows executables and installers are now https://support.microsoft.com/en-us/help/4472027/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus[signed using SHA-2 only].
* Save RTP stream to .au supports any codec with 8000 Hz rate supported by Wireshark (shown in RTP player). If save of audio is not possible (unsupported codec or rate), silence of same length is saved and warning is shown.
* Asynchronous DNS resolution is always enabled. As a result, the c-ares library is now a required dependency.
* Protobuf fields can be dissected as Wireshark (header) fields that allows user input
  the full names of Protobuf fields or messages in Filter toolbar for searching.
* Dissectors based on Protobuf can register themselves to a new 'protobuf_field' dissector table,
  which is keyed with the full names of fields, for further parsing fields of BYETS or STRING type.
* Wireshark is able to decode, play, and save iLBC payload on platforms where the https://github.com/TimothyGu/libilbc[iLBC library] is available.
* “Decode As” entries can now be copied from other profiles using a button in the dialog.
* sshdump can now be copied to multiple instances. Each instance will show up a different interface and will have its own profile.
* The main window now supports a packet diagram view, which shows each packet as a textbook-style diagram.

// === Removed Features and Support

//=== Removed Dissectors

// === New File Format Decoding Support

// [commaize]
// --
// --

=== New Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
Arinc 615A (A615A)
Asphodel Protocol
AudioCodes Debug Recording (ACDR)
Bluetooth HCI ISO (BT HCI ISO)
Cisco MisCabling Protocol (MCP)
DCE/RPC IRemoteWinspool SubSystem, (IREMOTEWINSPOOL)
Dynamic Link Exchange Protocol (DLEP)
Fortinet Single Sign-on (FSSO)
FTDI Multi-Protocol Synchronous Serial Engine (FTDI MPSSE)
Hypertext Transfer Protocol Version 3 (HTTP3)
Java Debug Wire Protocol (JDWP)
LBM Stateful Resolution Service (LBMSRS)
Lithionics Battery Management
OBSAI UDP-based Communication Protocol (UDPCP)
Palo Alto Heartbeat Backup (PA-HB-Bak)
ScyllaDB RPC
Technically Enhanced Capture Module Protocol (TECMP)
Tunnel Extensible Authentication Protocol (TEAP)
UDP based FTP w/ multicast V5 (UFTP5)
USB Printer (USBPRINTER)
--

=== Updated Protocol Support

Too many protocols have been updated to list here.

=== New and Updated Capture File Support

// There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
[commaize]
--
MP4 (ISO/IEC 14496-12)
--

// === New and Updated Capture Interfaces support

//_Non-empty section placeholder._

// === Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be
found at https://www.wireshark.org/docs/

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Bugs and feature requests can be reported on https://gitlab.com/wireshark/wireshark/-/issues[the issue tracker].

// Official Wireshark training and certification are available from
// https://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
