include::attributes.asciidoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

This is the final release of the Wireshark 2.6 branch.
It will reach its official end of life on October 18, 2020.
If you are still using Wireshark 2.6 you are encouraged to upgrade to Wireshark 3.2.

=== Bug Fixes

The following vulnerabilities have been fixed:

// * Buildbot crash output: fuzz-2020-07-28-5905.pcap wsbuglink:16741[].
* wssalink:2020-11[]
MIME Multipart dissector crash.
wsbuglink:16741[].
// cveidlink:2020-xxxx[].
Fixed in master: 2411eae9ed
Fixed in master-3.2: 21f082cb6e
Fixed in master-3.0: 14e274f3be
Fixed in master-2.6: 5803c7b87b

// * ERROR:epan/proto.c:9868:hfinfo_number_value_format_display: code should not be reached wsbuglink:16816[].
* wssalink:2020-12[]
TCP dissector crash.
wsbuglink:16816[].
// cveidlink:2020-xxxx[].
Fixed in master: c4634b1e99
Fixed in master-3.2: e9b727595b
Fixed in master-3.0: 7f3fe6164a
Fixed in master-2.6: 9d7ab8b46f

* Buildbot crash output: fuzz-2020-07-28-5905.pcap wsbuglink:16741[].


The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark convinced you to switch seats on the plane while neglecting to tell you that its seat was noticeably moist.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log v2.6.21rc0.. | gsed -e 's/\(close\|fix\|resolv\)[^ ]* #/\nclose #/gI' | grep ^close | sed -e 's/close.*#\([1-9][0-9]*\).*/\1/' | sort -V -u` ; do "$(git rev-parse --show-toplevel)/tools/gen-bugnote" $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Buildbot crash output: randpkt-2019-04-01-28345.pcap wsbuglink:15661[].

* Buildbot crash output: fuzz-2020-07-28-5905.pcap wsbuglink:16741[].

* S1-U data forwarding info and S103 PDN data forwarding info IE's showing improper value wsbuglink:16777[].

* Wireshark fails to detect libssh >= 0.9.5 wsbuglink:16845[].

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
AARP
BSSMAP
GSM A RR
GTPv2
MIME Multipart
NCP
Q.933
S1AP
TCP
X2AP
--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --

=== New and Updated Capture Interfaces support

There is no new or updated capture file support in this release.
// [commaize]
// --
// --

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

The BER dissector might infinitely loop.
wsbuglink:1516[].

Capture filters aren't applied when capturing from named pipes.
wsbuglink:1814[].

Filtering tshark captures with read filters (`-R`) no longer works.
wsbuglink:2234[].

Application crash when changing real-time option.
wsbuglink:4035[].

Wireshark and TShark will display incorrect delta times in some cases.
wsbuglink:4985[].

Wireshark should let you work with multiple capture files. wsbuglink:10488[].

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

// Official Wireshark training and certification are available from
// http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
