= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

* The Windows installers now ship with Qt 5.6. Previously they shipped with Qt 5.3.

=== Bug Fixes

The following vulnerabilities have been fixed:

* ws-salink:2016-56[]
+
The Bluetooth L2CAP dissector could crash.
(ws-buglink:12825[])
//cve-idlink:2015-XXXX[]
// Fixed in master: 7be7320
// Fixed in master-2.2: 355b56b
// Fixed in master-2.0: N/A

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark accepted your prom invitation then cancelled at the last minute. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.2.1rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Flow Graph colored data arrows. (ws-buglink:12065[])

* Capture File Properties under Statistics Grayed Out after Stopping a Capture. (ws-buglink:12071[])

* Qt: Hidden columns displayed during live capture. (ws-buglink:12377[])

* Bad description for NBSS error code 0x81. (ws-buglink:12835[])

* Live capture from USBPcap fails immediately. (ws-buglink:12846[])

* Cannot decrypt EAP-TTLS traffic (not recognized as conversation). (ws-buglink:12879[])

* Export packet dissections Option disabled after capturing traffic. (ws-buglink:12898[])

* Failure to open file named with Chinese or other multibyte characters. (ws-buglink:12900[])

* k12 text file format causes errors. (ws-buglink:12903[])

* File | File Set | List Files dialog is blank. (ws-buglink:12904[])

* Decoding/Display of an INAP CONNECT message goes wrong for the Destination Routing Address part. (ws-buglink:12911[])

* TLS padding extension dissector length parsing bug. (ws-buglink:12922[])

* Diameter dictionary bugs. (ws-buglink:12927[])

* File open from menu bar with filter in place causes Wireshark to crash. (ws-buglink:12929[])

* CMake builds don't register the NCP dissector, so the resulting Wireshark/TShark crashes with NCP packets. (ws-buglink:12945[])

* Unable to capture USBPcap trace using tshark with extcap built. (ws-buglink:12949[])

* Multiple PortableApps instances can once again be run at the same time.

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
6LowPAN
BT L2CAP
CIP
DCOM IRemUnknown
Diameter
DMP
EAP
ISUP
NBT
NCP
NetFlow
SSL / TLS
U3V
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
Ascend
K12
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

=== Major API Changes

There are no major API changes in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Packet list rows are oversized.
(ws-buglink:4357[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
