include::attributes.asciidoc[]

= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following bugs have been fixed:

* ws-salink:2018-01[]
+
Multiple dissectors could crash.
(ws-buglink:14253[])
cve-idlink:2018-5336[]
// Fixed in master: 94479aded1, c51560985a
// Fixed in master-2.4: 374e3d4bcf, 87d86189cc
// Fixed in master-2.2: 4f4c95cf46, f6702e49a9

* ws-salink:2018-03[]
+
The IxVeriWave file parser could crash.
(ws-buglink:14297[])
cve-idlink:2018-5334[]
// Fixed in master: 5dbc1d8d1c
// Fixed in master-2.4: d6b2f2a6ce
// Fixed in master-2.2: dc308c05ba

* ws-salink:2018-04[]
+
The WCP dissector could crash.
(ws-buglink:14251[])
cve-idlink:2018-5335[]
// Fixed in master: a7e29d8b66
// Fixed in master-2.4: 568ccd2250
// Fixed in master-2.2: 086b87376b

Prior to this release dumpcap enabled the Linux kernel's BPF JIT
compiler via the `net.core.bpf_jit_enable` sysctl. This could make
systems more vulnerable to Spectre variant 1 (cve-idlink:2017-5753[])
and this feature has been removed (ws-buglink:14313[]).

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2014-2486[]
//* Wireshark keeps leaving voicemails advertising timeshare condominiums in Fresno. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.4.5rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Some keyboard shortcut mix-up has been resolved by assigning new shortcuts
  to Edit -> Copy methods.

* Remote interfaces are not saved. (ws-buglink:8557[])

* Additional grouping in Expert Information dialog. (ws-buglink:11753[])

* First start with non-empty extcap folder after install or reboot hangs at "initializing tap listeners". (ws-buglink:12845[])

* Can't hide expert categories in Expert Information. (ws-buglink:13831[])

* Expert info dialog should have "Collapse All"/"Expand All" options. (ws-buglink:13842[])

* SIP Statistics extract does not work. (ws-buglink:13942[])

* Service Response Time - SCSI dialog crashes. (ws-buglink:14144[])

* Wireshark & Tshark 2.4.2 core dumps with segmentation fault. (ws-buglink:14194[])

* SSH remote capture promiscuous mode. (ws-buglink:14237[])

* SOCKS pseudo header displays incorrect Version value. (ws-buglink:14262[])

* Only first variable of list is dissected in NTP Control request message. (ws-buglink:14268[])

* NTP Authenticator field dissection fails if padding is used. (ws-buglink:14269[])

* BSSAP packet dissector issue - BSSAP_UPLINK_TUNNEL_REQUEST message. (ws-buglink:14289[])

* "[Malformed Packet]" for Mobile IP (MIP) protocol. (ws-buglink:14292[])

* There is a potential buffer underflow in File_read_line function in epan/wslua/wslua_file.c file. (ws-buglink:14295[])

* Saving a temporary capture file may not result in the temporary file being removed. (ws-buglink:14298[])

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
Bluetooth
BSSAP
BT ATT
BT HCI
BT SMP
MIP
NTP
SCTP
SOCKS
UDS
WCP
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
Ixia IxVeriWave
--sort-and-group--

//=== New and Updated Capture Interfaces support

//_Non-empty section placeholder._
//--sort-and-group--
//--sort-and-group--

//=== Major API Changes

//_Non-empty section placeholder._

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
