= Wireshark wireshark-version:[] Release Notes
// $Id$

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed.

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* ws-salink:2013-11[]
//* cve-idlink:2013-2486[]

* ws-salink:2013-41[]
+
The DCP ETSI dissector could crash.
// Fixed in trunk: r49802
// Fixed in trunk-1.10: r49819
// Fixed in trunk-1.8: r49818
// Fixed in trunk-1.6: r49822
(ws-buglink:8717[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
+
cve-idlink:2013-4083[]

* ws-salink:2013-42[]
+
The P1 dissector could crash. Discovered by Laurent Butti.
// Fixed in trunk: r50083
// Fixed in trunk-1.10: r50253
(ws-buglink:8826[])
+
Versions affected: 1.10.0
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-43[]
+
The Radiotap dissector could crash. Discovered by Laurent Butti.
// Fixed in trunk: r50090
// Fixed in trunk-1.10: r50214
(ws-buglink:8830[])
+
Versions affected: 1.10.0
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-44[]
+
The DCOM ISystemActivator dissector could crash. Discovered by Laurent Butti.
// Fixed in trunk: r50094
// Fixed in trunk-1.10: r50250
(ws-buglink:8828[])
+
Versions affected: 1.10.0
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-45[]
+
The Bluetooth SDP dissector could go into a large loop. Discovered by Laurent Butti.
// Fixed in trunk: r50134
// Fixed in trunk-1.10: r50250
// Fixed in trunk-1.8: r50251
(ws-buglink:8831[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-46[]
+
The Bluetooth OBEX dissector could go into an infinite loop.
// Fixed in trunk: r50258
// Fixed in trunk-1.10: r50259
(ws-buglink:8875[])
+
Versions affected: 1.10.0
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-47[]
+
The DIS dissector could go into a large loop.
// Fixed in trunk: r50450
// Fixed in trunk-1.10: r50451
// Fixed in trunk-1.8: r50452
(ws-buglink:8911[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-48[]
+
The DVB-CI dissector could crash. Discovered by Laurent Butti.
// Fixed in trunk: r50474
// Fixed in trunk-1.10: r50475
// Fixed in trunk-1.8: r50476
(ws-buglink:8916[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-49[]
+
The GSM RR dissector (and possibly others) could go into a large loop.
// Fixed in trunk: r50504
// Fixed in trunk-1.10: r50505
// Fixed in trunk-1.8: r50506
(ws-buglink:8923[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-50[]
+
The GSM A Common dissector could crash.
// Fixed in trunk: r50672
// Fixed in trunk-1.10: r50673
// Fixed in trunk-1.8: r50675
(ws-buglink:8940[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-51[]
+
The Netmon file parser could crash.
// Fixed in trunk: r49697
// Fixed in trunk-1.10: r50683
// Fixed in trunk-1.8: r50684
(ws-buglink:8742[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]

* ws-salink:2013-52[]
+
The ASN.1 PER dissector could crash. Discovered by Oliver-Tobias Ripka.
// Fixed in trunk: r49985
// Fixed in trunk-1.10: r50702
// Fixed in trunk-1.8: r50703
(ws-buglink:8722[])
+
Versions affected: 1.10.0, 1.8.0 to 1.8.7
//+
//cve-idlink:GENERIC-MAP-NOMATCH[]


The following bugs have been fixed:

//* Wireshark will practice the jazz flute for hours on end when you're trying to sleep. ws-buglink:0000[]

* Mark retransmitted SYN and FIN packets as retransmissions.

* Wireshark hides under Taskbar. (ws-buglink:3034)

* Add MAC-DATA support to TETRA dissector and other minor improvements. (ws-buglink:8708)

* Crash analyzing VoIP Calls (T38). (ws-buglink:8736)

* Wireshark writes empty NRB FQDN which makes trace unloadable. (ws-buglink:8763)

* Quick launch icon is absent, so it shows up as a generic icon. (ws-buglink:8773)

* Wrong encoding for 2 pod files, UTF-8 characters in another. (ws-buglink:8774)

* SCSI (SPC) sense key specific information field must not include SKSV. (ws-buglink:8782)

* Wireshark crashes when closing Flow Graph with Graph Analysis opened. (ws-buglink:8793)

* Strange behavior of tree expand/collapse in packet details. (ws-buglink:8908)

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--

Bluetooth OBEX
Bluetooth SDB
DCOM ISystemActivator
DCP ETSI
DIS
DVB-CI
GSM Common
GSM SMS
H.235
P1
Radiotap
SCSI
TETRA
VNC

--sort-and-group--

=== New and Updated Capture File Support

--sort-and-group--

Microsoft Network Monitor, pcap-ng.

--sort-and-group--

== Getting Wireshark

Wireshark source code and installation packages are available from
http://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the http://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814)

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Summary pane selected frame highlighting not maintained.
(ws-buglink:4445[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

== Getting Help

Community support is available on http://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on http://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
http://www.wireshark.org/faq.html[Wireshark web site].
