include::attributes.asciidoc[]
:stylesheet: ws.css
:linkcss:

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What’s New

The Windows installers now ship with Qt 5.12.5. They previously shipped
with Qt 5.12.4.

[[npcap_upgrade]]
If you have Npcap 0.994 or 0.995 installed, your system might crash when upgrading.
We recommend that you uninstall these versions manually prior to installing Wireshark.
See Npcap bugs https://github.com/nmap/nmap/issues/1591[1591] and https://github.com/nmap/nmap/issues/1675[1675] for more details.
You can uninstall either version manually by doing the following:

. Open a command or PowerShell prompt as Administrator and run `sc.exe config npcap start=disabled`.
. Run `sc.exe config npf start=disabled`. This will fail if WinPcap compatibility mode isn't enabled, but is otherwise harmless.
. Reboot (optional).
. Open “Programs and Features” in the Control Panel or “Apps & features” in Settings and uninstall Npcap.
. Open “Device Manager” (`devmgmt.msc`) in the Control Panel and expand the “Network adapters” section.
Uninstall each “Npcap Loopback Adapter” that you find.

=== Bug Fixes

The following vulnerabilities have been fixed:

// * wssalink:2019-22[]
// Foo dissector {crash,infinite loop}.
// wsbuglink:xxxxx[].
// cveidlink:2019-XXXXX[].
// Fixed in master: xxxxx
// Fixed in master-3.0: xxxxx
// Fixed in master-2.6: xxxxx

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark slowly leaked water under the kitchen sink over the course of several months, causing a big mess.
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v3.0.6rc0..| grep ' Bug:' | awk '{print $2}' | sort -n -u ` ; do "$(git rev-parse --show-toplevel)/tools/gen-bugnote" $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Qt interface crashes on a profile with packet list only. wsbuglink:16048[].

* Wireshark 3.0.4 does not start on macOS 10.13 after an upgrade from 3.0.3. wsbuglink:16050[].

* NET-SNMP EngineID Length handling Warning. wsbuglink:16051[].

* Upgrade from Wireshark 3.0.2/3.0.3 to 3.0.4/later is confusing and may not complete properly. wsbuglink:16052[].

* Crash SIGSEGV when decrypting IEEE 802.11 EAP re-authentications. wsbuglink:16058[].

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

// === New File Format Decoding Support

// [commaize]
// --
// --

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
[commaize]
--
--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
[commaize]
// --
// --

=== New and Updated Capture Interfaces support

There is no new or updated capture file support in this release.
// [commaize]
// --
// --

// === Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be
found at https://www.wireshark.org/docs/

Community support is available on https://ask.wireshark.org/[Wireshark’s
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark’s mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Bugs and feature requests can be reported on
https://bugs.wireshark.org/[the bug tracker].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
