include::attributes.asciidoc[]

= Wireshark {wireshark-version} Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

* wssalink:2018-51[]
The Wireshark dissection engine could crash.
wsbuglink:14466[].
cveidlink:2018-19625[].
// Fixed in master: ec5adb0ce9
// Fixed in master-2.6: f489f8f2c4
// Fixed in master-2.4: dc4d209f39

* wssalink:2018-52[]
The DCOM dissector could crash.
wsbuglink:15130[].
cveidlink:2018-19626[].
// Fixed in master: ec6ace066a
// Fixed in master-2.6: 26c6460e3c
// Fixed in master-2.4: c5a65115eb

* wssalink:2018-53[]
The LBMPDM dissector could crash.
wsbuglink:15132[].
cveidlink:2018-19623[].
// Fixed in master: 5797f60274
// Fixed in master-2.6: 1ec5a933e1
// Fixed in master-2.4: 9c8645ec7b

* wssalink:2018-54[]
The MMSE dissector could go into an infinite loop.
wsbuglink:15250[].
cveidlink:2018-19622[].
// Fixed in master: 1ddaf1a094
// Fixed in master-2.6: 1dddeff985
// Fixed in master-2.4: 3b7555d32d

* wssalink:2018-55[]
The IxVeriWave file parser could crash.
wsbuglink:15279[].
cveidlink:2018-19627[].
// Fixed in master: 332df929a9
// Fixed in master-2.6: bdc33cfaec
// Fixed in master-2.4: d9b8b93f0e

* wssalink:2018-56[]
The PVFS dissector could crash.
wsbuglink:15280[].
cveidlink:2018-19624[].
// Fixed in master: a8c93de0b0
// Fixed in master-2.6: 457420a638
// Fixed in master-2.4: 3e319db110

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark keeps leaving voicemails advertising timeshare condominiums in Fresno. (wsbuglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.4.12rc0..| grep ' Bug:' | awk '{print $2}' | sort -n -u ` ; do ./tools/gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* VoIP Calls dialog doesn't include RTP stream when preparing a filter. wsbuglink:13440[].

* Wireshark installs on macOS with permissions for /Library/Application Support/Wireshark that are too restrictive. wsbuglink:14335[].

* Closing Enabled Protocols dialog crashes wireshark. wsbuglink:14349[].

* Encrypted Alerts corresponds to a wrong selection in the packet bytes pane. wsbuglink:14712[].

* MATE unable to extract fields for PDU. wsbuglink:15208[].

* Malformed Packet: SV. wsbuglink:15224[].

* ISUP (ANSI) packets malformed in WS versions later than 2.4.8. wsbuglink:15236[].

* Handover candidate enquire message not decoded. wsbuglink:15237[].

* MLE security suite display incorrect. wsbuglink:15288[].

* Message for incorrect IPv4 option lengths is incorrect. wsbuglink:15290[].

* TACACS+ dissector does not properly reassemble large accounting messages. wsbuglink:15293[].

* NLRI of S-PMSI A-D BGP route not being displayed. wsbuglink:15307[].

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

//=== New File Format Decoding Support

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
BGP
DCOM
GSM A BSSMAP
IEEE 802.11 Radiotap
ISUP
LBMPDM
LISP
MLE
MMSE
PVFS
SLL
SSL/TLS
SV
TACACS+
--sort-and-group--

=== New and Updated Capture File Support

//There is no new or updated capture file support in this release.
--sort-and-group--
3GPP TS 32.423 Trace
IxVeriWave
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.
//--sort-and-group--
//--sort-and-group--

//=== Major API Changes

//_Non-empty section placeholder._

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(wsbuglink:1419[])

The BER dissector might infinitely loop.
(wsbuglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(wsbuglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(wsbuglink:2234[])

Application crash when changing real-time option.
(wsbuglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(wsbuglink:4985[])

Wireshark should let you work with multiple capture files. (wsbuglink:10488[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
