= Wireshark wireshark-version:[] Release Notes
// AsciiDoc quick reference: http://powerman.name/doc/asciidoc

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

=== Bug Fixes

The following vulnerabilities have been fixed:

//* ws-salink:2016-63[]
//+
//A dissector went awry.
//(ws-buglink:xxxx[])
//cve-idlink:2015-XXXX[]
// Fixed in master: xxxx
// Fixed in master-2.2: xxxx
// Fixed in master-2.0: xxxx

The following bugs have been fixed:

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* cve-idlink:2016-7000[]
//* Wireshark insists on calling you on your land line which is keeping you from abandoning it for cellular. (ws-buglink:0000[])
// cp /dev/null /tmp/buglist.txt ; for bugnumber in `git log --stat v2.0.10rc0..| grep ' Bug:' | cut -f2 -d: | sort -n -u ` ; do gen-bugnote $bugnumber; pbpaste >> /tmp/buglist.txt; done

* Duplicated Interfaces instances while refreshing. (ws-buglink:11553[])

* Time zone name needs to be converted to UTF-8 on Windows. (ws-buglink:11785[])

* Crash on fast local interface changes. (ws-buglink:12263[])

* SMTP BDAT dissector not reverting to command-code after DATA. (ws-buglink:13030[])

* Wireshark fails to recognize V6 DBS Etherwatch capture files. (ws-buglink:13093[])

* PPP BCP BPDU size reports not header size, but all data underneath and its header size in UI. (ws-buglink:13188[])

* Uninitialized memcmp on data in daintree-sna.c. (ws-buglink:13246[])

* UDLD flags are at other end of octet. (ws-buglink:13280[])

* MS-WSP dissector no longer works since commit 8c2fa5b5cf789e6d0d19cd0dd34479d0203d177a. (ws-buglink:13299[])

* TBCD string decoded wrongly in MAP ATI message. (ws-buglink:13316[])

* Filter Documentation: The tilde (~) operator is not documented. (ws-buglink:13320[])

=== New and Updated Features

There are no new features in this release.

//=== Removed Dissectors

=== New File Format Decoding Support

There are no new file formats in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--
DVB-CI
GSM MAP
ISAKMP
MS-WSP
PPP
QUIC
SMTP
UDLD
--sort-and-group--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
--sort-and-group--
Daintree SNA
DBS Etherwatch
--sort-and-group--

=== New and Updated Capture Interfaces support

There are no new or updated capture interfaces supported in this release.

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the https://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with read filters (-R) no longer works.
(ws-buglink:2234[])

Application crash when changing real-time option.
(ws-buglink:4035[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark should let you work with multiple capture files. (ws-buglink:10488[])

Dell Backup and Recovery (DBAR) makes many Windows applications crash,
including Wireshark. (ws-buglink:12036[])

== Getting Help

Community support is available on https://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on https://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
