include::attributes.adoc[]
:stylesheet: ws.css
:linkcss:
:copycss: {stylesheet}

== Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

== What’s New

__This is the last release branch with support for 32-bit Windows.__
Updates will no longer be available after May 22, 2024 for that platform.
wsbuglink:17779[]

// The Windows installers now ship with Npcap 1.60.
// They previously shipped with Npcap 1.55.

// The Windows installers now ship with USBPcap 1.5.X.0.
// They previously shipped with USBPcap 1.5.4.0.

// The Windows installers now ship with Qt 5.15.2.
// They previously shipped with Qt 5.12.1.

If you’re running Wireshark on macOS and upgraded to macOS 13 from an earlier version, you might have to open and run the “Uninstall ChmodBPF” package, then open and run “Install ChmodBPF” in order to reset the ChmodBPF Launch Daemon.
wsbuglink:18734[].

=== Bug Fixes

The following vulnerabilities have been fixed:

* wssalink:2023-24[]
BT SDP dissector infinite loop.
wsbuglink:19258[].
// cveidlink:2023-xxx[].
// Fixed in master: ef9c79ae81
// Fixed in release-4.0: ac20bfe644
// Fixed in release-3.6: d3068e8d2e
// CVSS AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
// CWE-835

* wssalink:2023-25[]
BT SDP dissector memory leak.
wsbuglink:19259[].
// cveidlink:2023-xxx[].
// Fixed in master: 7fecc31427,d086f2733b
// Fixed in release-4.0: 63005cc3df,0448263194
// Fixed in release-3.6: 016af38af0,863f6c3dc7
// CVSS AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
// CWE-401

* wssalink:2023-26[]
CP2179 dissector crash.
wsbuglink:19229[].
// cveidlink:2023-xxx[].
// Fixed in master: 44dc70cc5a
// Fixed in release-4.0: ce294d972a
// Fixed in release-3.6: 0b874ad0f5
// CVSS AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L
// CWE-369

The following bugs have been fixed:

//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark keeps banging out random chords on your piano and yelling “LIPS LIKE SUGUAR, SUGAR KISSES” because it was funny that one time at a party.

* Wireshark wrongly blames group membership when pcap capabilities are removed. wsbuglink:18279[].

* Packet bytes window broken layout. wsbuglink:18326[].

* Valid Ethernet CFM DMM packets are shown as malformed. wsbuglink:19198[].

* The QUIC dissector is reporting the quic_transport_parameters max_ack_delay with the title "GREASE". wsbuglink:19209[].

* Preferences: Folder name editing behaves weirdly, cursor jumps. wsbuglink:19213[].

* DHCPFO: Expert info list does not show all expert infos. wsbuglink:19216[].

* Applying Color filtering fails when selecting the same field to color (i.e., changing frames without focusing in packet details). wsbuglink:19249[].

* NAS 5GS Malformed Packet Decoding SOR transparent container PLMN ID and access technology list. wsbuglink:19273[].


=== New and Updated Features

// === Removed Features and Support

// === Removed Dissectors

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

// Add one protocol per line between the -- delimiters.
// ag -A1 '(define PSNAME|proto_register_protocol[^_])' $(git diff --name-only v3.6.16.. | ag packet- | sort -u)
[commaize]
--
BT SDP
CP2179
CQL
DHCPFO
F1AP
GSM DTAP
IEEE 802.11
NAS-5GS
PFCP
TFTP
--

=== New and Updated Capture File Support

There is no new or updated capture file support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --

=== New File Format Decoding Support

There is no new or updated file format support in this release.
// Add one file type per line between the -- delimiters.
// [commaize]
// --
// --


// === New and Updated Capture Interfaces support

//_Non-empty section placeholder._

// === Major API Changes

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages.
You can usually install or upgrade Wireshark using the package management system specific to that platform.
A list of third-party packages can be found on the
https://www.wireshark.org/download.html[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference files, plugins, SNMP MIBS, and RADIUS dictionaries.
These locations vary from platform to platform.
You can use menu:Help[About Wireshark,Folders] or `tshark -G folders` to find the default locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be found at
https://www.wireshark.org/docs/

Community support is available on
https://ask.wireshark.org/[Wireshark’s Q&A site]
and on the wireshark-users mailing list.
Subscription information and archives for all of Wireshark’s mailing lists can be found on
https://www.wireshark.org/lists/[the web site].

Bugs and feature requests can be reported on
https://gitlab.com/wireshark/wireshark/-/issues[the issue tracker].

// Official Wireshark training and certification are available from
// https://www.wiresharktraining.com/[Wireshark University].

== How You Can Help

The Wireshark Foundation helps as many people as possible understand their networks as much as possible.
You can find out more and donate at https://wiresharkfoundation.org[wiresharkfoundation.org].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
