= Wireshark wireshark-version:[] Release Notes

== What is Wireshark?

Wireshark is the world's most popular network protocol analyzer. It is
used for troubleshooting, analysis, development and education.

== What's New

Wireshark 1.8 reached end of life on June 21, 2014. 1.8.15 was the last official
release of that branch. If you are still running Wireshark 1.8 or earlier we
strongly recommend upgrading to the latest stable release.

=== Bug Fixes

//The following vulnerabilities have been fixed.

//* ws-buglink:5000[]
//* ws-buglink:6000[Wireshark bug]
//* ws-salink:2013-11[]
//* cve-idlink:2013-2486[]

//* ws-salink:2014-08[]
//+
//A dissector went awry.
// Fixed in master: ga1b2c3d4
// Fixed in master-1.10: ga1b2c3d4
// Fixed in master-1.8: ga1b2c3d4
//(ws-buglink:0000[])
//+
//Versions affected: 1.10.0 to 1.10.7, 1.8.0 to 1.8.14
//+
//cve-idlink:2014-0000[]

The following bugs have been fixed:

// Should be sorted numerically.
//* Wireshark will strip the paint off your car, then apply a hideous
//flame job to the hood and fenders using gray, red, and black primer.
//(ws-buglink:0000[])

=== New and Updated Features

There are no new features in this release.

=== New Protocol Support

There are no new protocols in this release.

=== Updated Protocol Support

--sort-and-group--

--sort-and-group--

=== New and Updated Capture File Support

--sort-and-group--

--sort-and-group--

=== Getting Wireshark

Wireshark source code and installation packages are available from
http://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages. You can
usually install or upgrade Wireshark using the package management system
specific to that platform. A list of third-party packages can be found
on the http://www.wireshark.org/download.html#thirdparty[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference
files, plugins, SNMP MIBS, and RADIUS dictionaries. These locations vary
from platform to platform. You can use About→Folders to find the default
locations on your system.

== Known Problems

Dumpcap might not quit if Wireshark or TShark crashes.
(ws-buglink:1419[])

The BER dissector might infinitely loop.
(ws-buglink:1516[])

Capture filters aren't applied when capturing from named pipes.
(ws-buglink:1814[])

Filtering tshark captures with display filters (-R) no longer works.
(ws-buglink:2234[])

The 64-bit Windows installer does not support Kerberos decryption.
(https://wiki.wireshark.org/Development/Win64[Win64 development page])

Application crash when changing real-time option.
(ws-buglink:4035[])

Hex pane display issue after startup.
(ws-buglink:4056[])

Packet list rows are oversized.
(ws-buglink:4357[])

Summary pane selected frame highlighting not maintained.
(ws-buglink:4445[])

Wireshark and TShark will display incorrect delta times in some cases.
(ws-buglink:4985[])

Wireshark may not dissect GSM A packets correctly. (ws-buglink:8940)

== Getting Help

Community support is available on http://ask.wireshark.org/[Wireshark's
Q&A site] and on the wireshark-users mailing list. Subscription
information and archives for all of Wireshark's mailing lists can be
found on http://www.wireshark.org/lists/[the web site].

Official Wireshark training and certification are available from
http://www.wiresharktraining.com/[Wireshark University].

== Frequently Asked Questions

A complete FAQ is available on the
http://www.wireshark.org/faq.html[Wireshark web site].
