include::attributes.adoc[]
:stylesheet: ws.css
:linkcss:
:copycss: {css_dir}/{stylesheet}

= Wireshark {wireshark-version} Release Notes
// Asciidoctor Syntax Quick Reference:
// https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

This is an experimental release intended to test new features for Wireshark 5.0.

== What is Wireshark?

Wireshark is the world’s most popular network protocol analyzer.
It is used for troubleshooting, analysis, development and education.

Wireshark is hosted by the Wireshark Foundation, a nonprofit which promotes protocol analysis education.
Wireshark and the foundation depend on your contributions in order to do their work.
If you or your organization would like to contribute or become a sponsor, please visit https://wiresharkfoundation.org[wiresharkfoundation.org].

== What’s New

// Add a summary of **major** changes here.
// Add other changes to "New and Updated Features" below.

Many other improvements have been made.
See the “New and Updated Features” section below for more details.

//=== Bug Fixes

//The following bugs have been fixed:
//* wsbuglink:5000[]
//* wsbuglink:6000[Wireshark bug]
//* cveidlink:2014-2486[]
//* Wireshark keeps waving its finger about an inch from you and saying "I'm not touching you."

=== New and Updated Features

The following features are either new or have been significantly updated since version 4.6.0:

// * The Windows installers now ship with Npcap 1.83.
//   They previously shipped with Npcap 1.79.

// * The Windows installers now ship with Qt 6.8.3.
//   They previously shipped with Qt 6.5.3.

* The keyboard shortcuts dialog (menu:About Wireshark[Keyboard Shortcuts]) has been moved out of of the About dialog to the menu:View[Internals,Keyboard Shortcuts] menu and now has a button to print the list of keyboard shortcuts to an HTML file.

* The application icons have been updated and refreshed.
  The macOS icon now supports Liquid Glass and is sized according to Apple's specifications on older macOS versions.
  wsbuglink:18131[]

// === Removed Features and Support

// === Removed Dissectors


=== New File Format Decoding Support

[commaize]
--
M-Module
--

=== New Protocol Support

// Add one protocol per line between the -- delimiters in the format
// “Full protocol name (Abbreviation)”
// git log --oneline --diff-filter=A --stat v4.7.0rc0.. epan/dissectors plugins
[commaize]
--
DCERPC SCARD_PACK
ESUN
Linux mac80211_hwsim Netlink
MCData
Mikrotik RoMON
Multicast Router Discovery (MRD)
NATS
NMEA 2000
Object Transform Protocol (OTP)
Perforce P4RPC
PosiStageNet (PSN)
TrueConf Protocol (TrueConf)
RDP Conctrl virtual channel Protocol (CONCTRL)
RDP Video Capture Virtual Channel Extension (RDPECAM)
Real-Time Tracking Protocol (RTTrP)
TrueConf
Ultra Ethernet Transport (UET)
ZigBee ZCL Generic Tunnel
Qualcomm Diagnostic (QCDIAG)
--

=== Updated Protocol Support

Too many protocol updates have been made to list them all here.

== New and Updated Capture File Support

[commaize]
--
--

=== New and Updated Capture Interface support

// [commaize]
// --
// --

//=== New and Updated Codec support

//_Non-empty section placeholder._

=== Major API Changes

The tvb new_subset and tvb length_remaining routines now take unsigned offset
and length arguments. Negative offsets, indicating an offset relative to the
end of the _captured_ length of the buffer (not reported) are no longer
permitted, nor is a length of -1 meaning "to the end of the buffer." For
the latter, use tvb_new_subset_remaining instead. Internally, tvbuffer lengths
have long been unsigned; this change should simplify dealing with 32-bit
unsigned length fields and checking for offsets overflowing.

=== Plugin Development Changes

The list of installed dissector header files has been reduced and is now restricted to ones that contain the following:
- Functions marked WS_DLL_PUBLIC
- Structs whose names contain "tap_"
- The string "PUBLIC_HEADER"

== Getting Wireshark

Wireshark source code and installation packages are available from
https://www.wireshark.org/download.html.

=== Vendor-supplied Packages

Most Linux and Unix vendors supply their own Wireshark packages.
You can usually install or upgrade Wireshark using the package management system specific to that platform.
A list of third-party packages can be found on the
https://www.wireshark.org/download.html[download page]
on the Wireshark web site.

== File Locations

Wireshark and TShark look in several different locations for preference files, plugins, SNMP MIBS, and RADIUS dictionaries.
These locations vary from platform to platform.
You can use menu:Help[About Wireshark,Folders] or `tshark -G folders` to find the default locations on your system.

== Getting Help

The User’s Guide, manual pages and various other documentation can be found at
https://www.wireshark.org/docs/

Community support is available on
https://ask.wireshark.org/[Wireshark’s Q&A site]
and on the wireshark-users mailing list.
Subscription information and archives for all of Wireshark’s mailing lists can be found on https://lists.wireshark.org/lists/[the mailing list site].

Bugs and feature requests can be reported on
https://gitlab.com/wireshark/wireshark/-/issues[the issue tracker].

You can learn protocol analysis and meet Wireshark’s developers at
https://sharkfest.wireshark.org[SharkFest].

Official Wireshark training and certification are available from
https://www.wireshark.org/certifications[the Wireshark Foundation].

== How You Can Help

The Wireshark Foundation helps as many people as possible understand their networks as much as possible.
You can find out more and donate at https://wiresharkfoundation.org[wiresharkfoundation.org].

== Frequently Asked Questions

A complete FAQ is available on the
https://www.wireshark.org/faq.html[Wireshark web site].
