## Makefile for building wireshark.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#

include ..\config.nmake
include ..\Makefile.nmake.inc

############### no need to modify below this line #########

include Makefile.common

CFLAGS=$(WARNINGS_ARE_ERRORS) $(STANDARD_CFLAGS) \
	/I. /I.. $(GLIB_CFLAGS) \
	/I$(PCAP_DIR)\include -DWS_BUILD_DLL

.c.obj::
   $(CC) $(CFLAGS) -Fd.\ -c $<

# no fork() on windows this needs some thoughts... 
