#! /bin/sh
#
# Fix a Qt .pc file's flags.
#
# Wireshark - Network traffic analyzer
# By Gerald Combs <gerald@wireshark.org>
# Copyright 2014 Gerald Combs
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Fix a single Qt .pc file to provide the right flags; a -F flag is
# needed to point to the directory under which the frameworks are
# placed, and a -I flag needs to point to the directory where
# the include files for the component in question are place in
# the framework's directory hierarchy, rather thany to where the
# include files *would* be if the component *weren't* distributed
# as a framework.
#
ed - "$1" <<EOF
H
/^Cflags: /s;-I\${includedir}/\([A-Za-z0-9]*\);-I\${libdir}/\1.framework/Versions/5/Headers;
/^Cflags: /s;;Cflags: -F\${libdir} ;
w
q
