#
# $Id: Makefile.nmake,v 1.2 2003/11/18 19:18:45 ulfl Exp $
#

include ..\..\config.nmake

############### no need to modify below this line #########

CFLAGS=/DHAVE_CONFIG_H /I../.. /I../../wiretap $(GLIB_CFLAGS) \
	/I$(PCAP_DIR)\include -D_U_="" $(LOCAL_CFLAGS)

OBJECTS=packet-rdm.obj 

rdm.dll rdm.exp rdm.lib : $(OBJECTS) ..\plugin_api.obj
	link -dll /out:rdm.dll $(OBJECTS) ..\plugin_api.obj \
	$(GLIB_LIBS)

clean:
	rm -f $(OBJECTS) rdm.dll rdm.exp rdm.lib $(PDB_FILE)

distclean: clean
