usr/lib/*/libwireshark.so
usr/lib/*/pkgconfig/wireshark.pc
color.h usr/include/wireshark
obj-*/config.h usr/include/wireshark
register.h usr/include/wireshark
stat_menu.h usr/include/wireshark
epan/*.h usr/include/wireshark/epan
epan/crypt/*.h usr/include/wireshark/epan/crypt
epan/dfilter/*.h usr/include/wireshark/epan/dfilter
epan/dissectors/*.h usr/include/wireshark/epan/dissectors
epan/ftypes/*.h usr/include/wireshark/epan/ftypes
epan/wmem/*.h usr/include/wireshark/epan/wmem
