## Makefile for building wireshark.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#
# $Id$

include ..\..\config.nmake

all : TPG.pm

clean:
	rm -f TPG.pm tpg.output

distclean: clean

maintainer-clean: distclean
