#
# $Id: Makefile.nmake,v 1.3 2003/06/14 20:45:28 guy Exp $
#

include ..\..\config.nmake

############### no need to modify below this line #########

CFLAGS=/DHAVE_CONFIG_H /I../.. /I../../wiretap $(GLIB_CFLAGS) \
	/I$(PCAP_DIR)\include -D_U_="" $(LOCAL_CFLAGS)

OBJECTS=packet-pcli.obj 

pcli.dll pcli.exp pcli.lib : packet-pcli.obj ..\plugin_api.obj
	link -dll /out:pcli.dll packet-pcli.obj ..\plugin_api.obj \
	$(GLIB_LIBS)

clean:
	rm -f $(OBJECTS) pcli.dll pcli.exp pcli.lib $(PDB_FILE)
