#! /bin/sh
#
# $Id$

#
# Unfortunately, Mac OS X's devfs is based on the old FreeBSD
# one, not the current one, so there's no way to configure it
# to create BPF devices with particular owners or groups.
# This startup item will make it owned by the admin group,
# with permissions rw-rw----, so that anybody in the admin
# group can use programs that capture or send raw packets.
#
# Change this as appropriate for your site, e.g. to make
# it owned by a particular user without changing the permissions,
# so only that user and the super-user can capture or send raw
# packets, or give it the permissions rw-r-----, so that
# only the super-user can send raw packets but anybody in the
# admin group can capture packets.
#
chgrp access_bpf /dev/bpf*
chmod g+rw /dev/bpf*

#
# As long as we're here with root privileges, see whether we have
# /opt/X11 but not /usr/X11 and, if so, create /usr/X11 as a symbolic
# link to /opt/X11.
#
# With XQuartz installed, the X11 directory is under /opt, with /usr/X11
# being a symbolic link to /opt/X11, for compatibility with X programs
# expecting X11 to be there.  (With Mountain Lion and later, without
# XQuartz installed, /usr/X11 is a directory tree containing enough of
# X11 to allow X11 programs to start but to pop up a "do you want to
# install XQuartz?" dialog, so that's where X programs *should* look
# for X11.)
#
# Unfortunately, if you have XQuartz installed on a pre-Yosemite
# release, and you upgrade to Yosemite, the Yosemite installer removes
# the /usr/X11 symlink, breaking X11 programs, so we should put it back.
#
# This will be run on system startup, so if a version of ChmodBPF with
# this code is already installed on the pre-Yosemite system, the
# Yosemite upgrade will cause a reboot, and this code will be run.
#
# This will also be run when installing a new version of Wireshark,
# so if you have a system with a broken XQuartz, and install a version
# of Wireshark with this code in it, this code will be run.
#
if [ -d /opt/X11 -a ! -e /usr/X11 ]
then
	#
	# We have a /opt/X11 directory and don't have /usr/X11.
	# Make the symlink.
	#
	ln -s /opt/X11 /usr/X11
fi
