#
# $Id$
#

include ..\..\config.nmake

############### no need to modify below this line #########

CFLAGS=/DHAVE_CONFIG_H /I../.. /I../../wiretap $(GLIB_CFLAGS) \
	/I$(PCAP_DIR)\include -D_U_="" $(LOCAL_CFLAGS)

OBJECTS=packet-megaco.obj 

megaco.dll megaco.exp megaco.lib : $(OBJECTS) ..\plugin_api.obj
	link -dll /out:megaco.dll $(OBJECTS) ..\plugin_api.obj \
	$(GLIB_LIBS)

clean:
	rm -f $(OBJECTS) megaco.dll megaco.exp megaco.lib $(PDB_FILE)

distclean: clean
