#! /bin/sh
#
# Fix a Qt .pc file's flags.
#
# Wireshark - Network traffic analyzer
# By Gerald Combs <gerald@wireshark.org>
# Copyright 2014 Gerald Combs
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Fix a single Qt .pc file to provide the right flags; a -F flag is
# needed to point to the directory under which the frameworks are
# placed, and a -I flag needs to point to the directory where
# the include files for the component in question are place in
# the framework's directory hierarchy, rather thany to where the
# include files *would* be if the component *weren't* distributed
# as a framework.
#
ed - "$1" <<EOF
H
/^Cflags: /s;-I\${includedir}/\([A-Za-z0-9]*\);-I\${libdir}/\1.framework/Versions/5/Headers;
/^Cflags: /s;;Cflags: -F\${libdir} ;
w
q
