#! /bin/sh
#
# Fix the .pc files for versions of Qt installed from binary packages.
#
# Wireshark - Network traffic analyzer
# By Gerald Combs <gerald@wireshark.org>
# Copyright 2014 Gerald Combs
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# See bug QTBUG-35256 for the full painful story.  Shorter version:
# the macOS Qt packages provide the Qt components as frameworks, but
# the .pc files don't generate the right CFLAGS/CXXFLAGS to make
# that work, so autoconf doesn't work correctly.
#
if [ "$#" != 1 ]
then
	echo "Usage: qt-fix-pc-files <top-level Qt directory>" 1>&1
	exit 1
fi
find "$1" -name "*.pc" -exec tools/macos-setup-patches/qt-fix-pc-file {} ";"
