#!/bin/bash
#
# Given a Wireshark bug ID, fetch its title and prepare an entry suitable
# for pasting into the release notes. Requires curl, grep, and sed.
#
# Usage: gen-bugnote <bug number>
#
# Copyright 2013 Gerald Combs
#
# SPDX-License-Identifier: GPL-2.0-or-later
#

bz_url_pfx="https://bugs.wireshark.org/bugzilla/show_bug.cgi"
bug_id="$1"

# Bugzilla gives us UTF-8 with HTML escapes. We want UTF-8. Recode assumes
# that HTML is encoded as ISO-8859-1.
# https://github.com/rrthomas/Recode/issues/1
recode_to_html_cmd="cat"
if hash recode > /dev/null 2>&1 ; then
    recode_to_html_cmd="recode utf8..html"
    recode_to_utf8_cmd="recode html..utf8"
fi

case "$OSTYPE" in
    darwin*)
        clipboard_cmd="pbcopy -Pascii"
        ;;
    cygwin*)
        clipboard_cmd="cat > /dev/clipboard"
        ;;
    linux*)
        clipboard_cmd="xsel --clipboard"
        ;;
    *)
        echo "Unable to copy to clipboard"
        clipboard_cmd="cat > /dev/null"
        ;;
esac

if [ -z "$bug_id" ] ; then
    echo "Usage: $( basename "$0" ) <bug id>"
    exit 1
fi

bug_title=$(
    curl -s -o - "${bz_url_pfx}?id=$bug_id" \
    | grep -i '<title>' \
    | sed \
        -e 's/{/\\{/g' \
        -e 's:.*<title>.*ndash; ::' \
        -e 's:</title>.*::g' \
        -e 's/[^\.]$/&./g' \
        -e 's/\\/{backslash}/g' \
    )

echo -e "* $bug_title wsbuglink:${bug_id}[].\\n" \
        | $recode_to_html_cmd \
        | $recode_to_utf8_cmd \
        | $clipboard_cmd

echo "Copied $bug_id: $bug_title"
