## Makefile for building ethereal.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#
# $Id: Makefile.nmake,v 1.5 2003/10/13 19:04:56 guy Exp $

all: lemon

clean:
	cd lemon
	$(MAKE) /$(MAKEFLAGS) -f Makefile.nmake clean
	cd ..

distclean: clean
	cd lemon
	$(MAKE) /$(MAKEFLAGS) -f Makefile.nmake distclean
	cd ..

lemon::
	cd lemon
	$(MAKE) /$(MAKEFLAGS) -f Makefile.nmake
	cd ..
