/* packet-bootparams.h */
/* $Id$ */

#ifndef PACKET_BOOTPARAMS_H
#define PACKET_BOOTPARAMS_H

#define BOOTPARAMSPROC_NULL 0
#define BOOTPARAMSPROC_WHOAMI 1
#define BOOTPARAMSPROC_GETFILE 2

#define BOOTPARAMS_PROGRAM 100026

#endif
