/* Do not modify this file. */
/* It was automatically generated by ../../tools/process-x11-xcb.pl
   using xcbproto version xcb-proto-1.17.0 */
/*
 * Copyright 2008, 2009, 2013, 2014 Open Text Corporation <pharris[AT]opentext.com>
 *
 * Wireshark - Network traffic analyzer
 * By Gerald Combs <gerald[AT]wireshark.org>
 * Copyright 1998 Gerald Combs
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

static const char * const bigreq_errors[] = {
  NULL
};

static const char * const composite_errors[] = {
  NULL
};

static const char * const damage_errors[] = {
  "damage-BadDamage",
  NULL
};

static const char * const dbe_errors[] = {
  "dbe-BadBuffer",
  NULL
};

static const char * const dpms_errors[] = {
  NULL
};

static const char * const dri2_errors[] = {
  NULL
};

static const char * const dri3_errors[] = {
  NULL
};

static const char * const ge_errors[] = {
  NULL
};

static const char * const glx_errors[] = {
  "glx-BadContext",
  "glx-BadContextState",
  "glx-BadDrawable",
  "glx-BadPixmap",
  "glx-BadContextTag",
  "glx-BadCurrentWindow",
  "glx-BadRenderRequest",
  "glx-BadLargeRequest",
  "glx-UnsupportedPrivateRequest",
  "glx-BadFBConfig",
  "glx-BadPbuffer",
  "glx-BadCurrentDrawable",
  "glx-BadWindow",
  "glx-GLXBadProfileARB",
  NULL
};

static const char * const present_errors[] = {
  NULL
};

static const char * const randr_errors[] = {
  "randr-BadOutput",
  "randr-BadCrtc",
  "randr-BadMode",
  "randr-BadProvider",
  NULL
};

static const char * const record_errors[] = {
  "record-BadContext",
  NULL
};

static const char * const render_errors[] = {
  "render-PictFormat",
  "render-Picture",
  "render-PictOp",
  "render-GlyphSet",
  "render-Glyph",
  NULL
};

static const char * const res_errors[] = {
  NULL
};

static const char * const screensaver_errors[] = {
  NULL
};

static const char * const shape_errors[] = {
  NULL
};

static const char * const shm_errors[] = {
  "shm-BadSeg",
  NULL
};

static const char * const sync_errors[] = {
  "sync-Counter",
  "sync-Alarm",
  NULL
};

static const char * const xc_misc_errors[] = {
  NULL
};

static const char * const xevie_errors[] = {
  NULL
};

static const char * const xf86dri_errors[] = {
  NULL
};

static const char * const xf86vidmode_errors[] = {
  "xf86vidmode-BadClock",
  "xf86vidmode-BadHTimings",
  "xf86vidmode-BadVTimings",
  "xf86vidmode-ModeUnsuitable",
  "xf86vidmode-ExtensionDisabled",
  "xf86vidmode-ClientNotLocal",
  "xf86vidmode-ZoomLocked",
  NULL
};

static const char * const xfixes_errors[] = {
  "xfixes-BadRegion",
  NULL
};

static const char * const xinerama_errors[] = {
  NULL
};

static const char * const xinput_errors[] = {
  "xinput-Device",
  "xinput-Event",
  "xinput-Mode",
  "xinput-DeviceBusy",
  "xinput-Class",
  NULL
};

static const char * const xkb_errors[] = {
  "xkb-Keyboard",
  NULL
};

static const char * const xprint_errors[] = {
  "xprint-BadContext",
  "xprint-BadSequence",
  NULL
};

static const char * const xselinux_errors[] = {
  NULL
};

static const char * const xtest_errors[] = {
  NULL
};

static const char * const xv_errors[] = {
  "xv-BadPort",
  "xv-BadEncoding",
  "xv-BadControl",
  NULL
};

static const char * const xvmc_errors[] = {
  NULL
};

