# Configure the Repo Lockdown GitHub App to automatically close pull requests.
# See https://github.com/dessant/repo-lockdown

name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Repo Lockdown'
        uses: dessant/repo-lockdown@v4
        with:
          pr-comment: >
            Hi, thank you for your contribution!

            GitHub is however not the right place for these. The development repository is
            hosted on GitLab: <https://gitlab.com/wireshark/wireshark>. Please have a look at
            <https://www.wireshark.org/docs/wsdg_html_chunked/ChSrcContribute.html>
            for further instructions.
