#!/bin/bash

hash optipng 2>/dev/null && HAVE_OPTIPNG="True"
hash optipng 2>/dev/null && HAVE_OPTIPNG="True"

find . -type f -name "*.png" | while read PNG_FILE ; do
    echo Compressing $PNG_FILE
    hash optipng 2>/dev/null  && optipng -o3 -quiet "$PNG_FILE"
    hash advpng 2>/dev/null   && advpng -z -4 "$PNG_FILE"
    hash advdef 2>/dev/null   && advdef -z -4 "$PNG_FILE"
    hash pngcrush 2>/dev/null && pngcrush -brute "$PNG_FILE"
done
