#!/bin/sh

RESOLUTIONS="64 48 32 16"

CONVERT=convert

for RES in 64 48 32 16 ; do
    $CONVERT -resize ${RES}x${RES} wsicon256.png wsicon${RES}.png
    $CONVERT -resize ${RES}x${RES} wsicon256.png wsicon${RES}.xpm
done

for RES in 48 32 16 ; do
    $CONVERT -resize ${RES}x${RES} wsiconcap256.png wsiconcap${RES}.xpm
done


